/*
 * Popular Dineout — Menu Schema + Seed Data
 *
 * Run this in the Supabase SQL Editor (Dashboard > SQL Editor > New Query).
 * It creates three tables, enables RLS with public read access, and inserts
 * all 14 categories, 185 menu items, and 7 combo thalis.
 *
 * Tables:
 *   menu_categories — 14 rows (13 regular + 1 combo-thalis section)
 *   menu_items      — 185 regular menu items
 *   combo_thalis    — 7 combo thali entries
 *
 * Security:
 *   RLS enabled on all tables.
 *   SELECT policies for anon + authenticated (public read).
 *   No write policies — data is managed via SQL only.
 */

CREATE TABLE IF NOT EXISTS menu_categories (
  id text PRIMARY KEY,
  label text NOT NULL,
  short_label text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  is_combo boolean NOT NULL DEFAULT false
);

ALTER TABLE menu_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_menu_categories" ON menu_categories;
CREATE POLICY "public_read_menu_categories"
  ON menu_categories FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS menu_items (
  id text PRIMARY KEY,
  category_id text NOT NULL REFERENCES menu_categories(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  price int NOT NULL,
  price_full int,
  image text NOT NULL,
  image_alt text NOT NULL DEFAULT '',
  diet text NOT NULL DEFAULT 'veg',
  spice text,
  popular boolean NOT NULL DEFAULT false,
  chef_special boolean NOT NULL DEFAULT false,
  serves text,
  sort_order int NOT NULL DEFAULT 0
);

ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_menu_items" ON menu_items;
CREATE POLICY "public_read_menu_items"
  ON menu_items FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS combo_thalis (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  price int NOT NULL,
  image text NOT NULL,
  image_alt text NOT NULL DEFAULT '',
  diet text NOT NULL DEFAULT 'veg',
  serves text NOT NULL DEFAULT '',
  items text[] NOT NULL DEFAULT '{}',
  popular boolean NOT NULL DEFAULT false,
  sort_order int NOT NULL DEFAULT 0
);

ALTER TABLE combo_thalis ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_combo_thalis" ON combo_thalis;
CREATE POLICY "public_read_combo_thalis"
  ON combo_thalis FOR SELECT TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_menu_items_category_id ON menu_items(category_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_sort_order ON menu_items(category_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_menu_categories_sort_order ON menu_categories(sort_order);
CREATE INDEX IF NOT EXISTS idx_combo_thalis_sort_order ON combo_thalis(sort_order);

-- Insert 14 categories (13 regular + 1 combo-thalis)
INSERT INTO menu_categories (id, label, short_label, sort_order, is_combo) VALUES
  ('beverages', 'Beverages — Sips & Brews', 'Beverages', 1, false),
  ('soups-shakes', 'Soul-Warming Soup + Shakes', 'Soup + Shakes', 2, false),
  ('quick-bites', 'Quick Bites — Rolls | Sandwiches | Snacks', 'Quick Bites', 3, false),
  ('indo-chinese', 'Appetizers — Indo-Chinese Starters', 'Indo-Chinese Starters', 4, false),
  ('tandoor-veg', 'Tandoor Se — Vegetarian Starters', 'Tandoor Veg', 5, false),
  ('tandoor-nonveg', 'Tandoor Se — Non-Veg Starters', 'Tandoor Non-Veg', 6, false),
  ('veg-main', 'Vegetarian Delights — Indian Main Course', 'Indian Veg Main Course', 7, false),
  ('nonveg-main', 'Royal Curries — Non-Veg Main Course', 'Non-Veg Main Course', 8, false),
  ('breads', 'Breads and Roti — Fresh from the Tandoor', 'Breads & Roti', 9, false),
  ('salad-raita', 'Fresh Greens — Salad & Raita', 'Salad & Raita', 10, false),
  ('desserts', 'Desserts', 'Desserts', 11, false),
  ('rice-biryani', 'Rice and Biryani — Classics with a Citrus Twist', 'Rice & Biryani', 12, false),
  ('noodles', 'Noodles — Wok Classics', 'Noodles', 13, false),
  ('combo-thalis', 'Popular\'s Special — Thali & Combos', 'Thali & Combos', 14, true)
ON CONFLICT (id) DO NOTHING;

-- Insert 185 menu items
INSERT INTO menu_items (id, category_id, name, description, price, price_full, image, image_alt, diet, spice, popular, chef_special, serves, sort_order) VALUES
  ('bv-001', 'beverages', 'Packaged Drinking Water', '1000ML — MRP', 20, NULL, 'https://images.pexels.com/photos/327090/pexels-photo-327090.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Packaged drinking water bottle', 'veg', NULL, false, false, '1000ML', 1),
  ('bv-002', 'beverages', 'Regular Hot Tea', 'Classic Indian tea brewed with milk and sugar.', 52, NULL, 'https://images.pexels.com/photos/12865880/pexels-photo-12865880.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Hot tea in a glass', 'veg', NULL, false, false, '200ML', 2),
  ('bv-003', 'beverages', 'Popular''s Special Masala Chai', 'Our signature masala chai with aromatic spices.', 59, NULL, 'https://images.pexels.com/photos/12865880/pexels-photo-12865880.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Masala chai with spices in a glass', 'veg', NULL, true, false, '200ML', 3),
  ('bv-004', 'beverages', 'Zesty Lemon Tea', 'Refreshing hot tea infused with fresh lemon.', 49, NULL, 'https://images.pexels.com/photos/2633403/pexels-photo-2633403.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Lemon tea in a cup', 'veg', NULL, false, false, '200ML', 4),
  ('bv-005', 'beverages', 'Classic Hot Coffee', 'Freshly brewed hot coffee, rich and aromatic.', 129, NULL, 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Hot coffee in a mug', 'veg', NULL, false, false, '200ML', 5),
  ('bv-006', 'beverages', 'Fresh Lime Water', 'Cooling lime water with a hint of mint.', 90, NULL, 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Fresh lime water with mint', 'veg', NULL, false, false, '300ML', 6),
  ('bv-007', 'beverages', 'Refreshing Fresh Lime Soda', 'Sparkling soda with fresh lime juice.', 119, NULL, 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Fresh lime soda in a glass', 'veg', NULL, false, false, '300ML', 7),
  ('bv-008', 'beverages', 'Desi Masala Chaas', 'Spiced buttermilk with cumin and curry leaves.', 109, NULL, 'https://images.pexels.com/photos/6808666/pexels-photo-6808666.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Masala chaas in a clay cup', 'veg', NULL, false, false, '200ML', 8),
  ('bv-009', 'beverages', 'Punjabi Sweet Lassi', 'Thick and creamy sweet yogurt drink.', 129, NULL, 'https://images.pexels.com/photos/18142603/pexels-photo-18142603.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Sweet lassi in a tall glass', 'veg', NULL, true, false, '200ML', 9),
  ('bv-010', 'beverages', 'Classic Salted Lassi', 'Refreshing salted yogurt drink with cumin.', 129, NULL, 'https://images.pexels.com/photos/18142603/pexels-photo-18142603.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Salted lassi in a glass', 'veg', NULL, false, false, '300ML', 10),
  ('bv-011', 'beverages', 'Assorted Soft Drinks', 'Choice of Pepsi, 7Up, Mirinda, and more.', 79, NULL, 'https://images.pexels.com/photos/2983100/pexels-photo-2983100.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Assorted soft drink bottles', 'veg', NULL, false, false, '200ML', 11),
  ('bv-012', 'beverages', 'Fizzy Masala Soda', 'Spiced carbonated soda with a tangy kick.', 89, NULL, 'https://images.pexels.com/photos/2983100/pexels-photo-2983100.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Masala soda in a bottle', 'veg', NULL, false, false, '300ML', 12),
  ('bv-013', 'beverages', 'Chatpata Masala Coke', 'Coke spiced with masala for a desi twist.', 109, NULL, 'https://images.pexels.com/photos/2983100/pexels-photo-2983100.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Masala coke in a glass', 'veg', NULL, false, false, '300ML', 13),
  ('bv-014', 'beverages', 'Chilled Cold Coffee', 'Iced cold coffee blended to perfection.', 189, NULL, 'https://images.pexels.com/photos/3908198/pexels-photo-3908198.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Cold coffee in a tall glass', 'veg', NULL, true, false, '300ML', 14),
  ('bv-015', 'beverages', 'Indulgent Cold Coffee with Ice Cream', 'Cold coffee topped with a scoop of ice cream.', 209, NULL, 'https://images.pexels.com/photos/17558645/pexels-photo-17558645.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Cold coffee with ice cream on top', 'veg', NULL, false, true, '300ML', 15),
  ('sp-001', 'soups-shakes', 'Classic Veg Manchow Soup', 'Spicy vegetable soup with fried noodles topping.', 209, NULL, 'https://images.pexels.com/photos/29631489/pexels-photo-29631489.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg Manchow soup with crispy noodles', 'veg', 'medium', false, false, '1 bowl', 1),
  ('sp-002', 'soups-shakes', 'Veg Hot & Sour Soup', 'Tangy and spicy vegetable soup with a bold kick.', 209, NULL, 'https://images.pexels.com/photos/29631468/pexels-photo-29631468.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Hot and sour vegetable soup', 'veg', 'hot', false, false, '1 bowl', 2),
  ('sp-003', 'soups-shakes', 'Rich Cream of Tomato Soup', 'Velvety tomato soup with fresh cream.', 199, NULL, 'https://images.pexels.com/photos/4062272/pexels-photo-4062272.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Cream of tomato soup', 'veg', NULL, false, false, '1 bowl', 3),
  ('sp-004', 'soups-shakes', 'Comforting Veg Sweet Corn Soup', 'Creamy sweet corn soup with vegetables.', 209, NULL, 'https://images.pexels.com/photos/29631481/pexels-photo-29631481.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Sweet corn vegetable soup', 'veg', NULL, false, false, '1 bowl', 4),
  ('sp-005', 'soups-shakes', 'Veg Noodle Soup', 'Hearty noodle soup with fresh vegetables.', 219, NULL, 'https://images.pexels.com/photos/8696758/pexels-photo-8696758.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Vegetable noodle soup', 'veg', NULL, false, false, '1 bowl', 5),
  ('sp-006', 'soups-shakes', 'Chef''s Special Chicken Manchow Soup', 'Spicy chicken soup topped with crispy noodles.', 219, NULL, 'https://images.pexels.com/photos/29631489/pexels-photo-29631489.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken Manchow soup with noodles', 'non-veg', 'medium', false, true, '1 bowl', 6),
  ('sp-007', 'soups-shakes', 'Chicken Hot & Sour Soup', 'Tangy and spicy chicken soup with vegetables.', 219, NULL, 'https://images.pexels.com/photos/29631468/pexels-photo-29631468.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken hot and sour soup', 'non-veg', 'hot', false, false, '1 bowl', 7),
  ('sp-008', 'soups-shakes', 'Comforting Chicken Sweet Corn Soup', 'Creamy sweet corn soup with shredded chicken.', 209, NULL, 'https://images.pexels.com/photos/29631481/pexels-photo-29631481.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken sweet corn soup', 'non-veg', NULL, false, false, '1 bowl', 8),
  ('sp-009', 'soups-shakes', 'Hearty Chicken Noodle Soup', 'Wholesome chicken noodle soup with vegetables.', 249, NULL, 'https://images.pexels.com/photos/8743923/pexels-photo-8743923.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken noodle soup', 'non-veg', NULL, false, false, '1 bowl', 9),
  ('sp-010', 'soups-shakes', 'Regular Milk Shake', 'Classic milk shake in your favourite flavour.', 159, NULL, 'https://images.pexels.com/photos/38178695/pexels-photo-38178695.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Regular milk shake in a glass', 'veg', NULL, false, false, '1 glass', 10),
  ('sp-011', 'soups-shakes', 'Classic Thick Milk Shake', 'Rich thick shake — Vanilla / Strawberry / Butterscotch / Chocolate.', 199, NULL, 'https://images.pexels.com/photos/6174870/pexels-photo-6174870.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Thick milk shake with whipped cream', 'veg', NULL, false, false, '1 glass', 11),
  ('sp-012', 'soups-shakes', 'Kit Kat Shake', 'Creamy shake loaded with crushed Kit Kat.', 209, NULL, 'https://images.pexels.com/photos/30660270/pexels-photo-30660270.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Kit Kat milk shake', 'veg', NULL, true, false, '1 glass', 12),
  ('sp-013', 'soups-shakes', 'Oreo Cookie Shake', 'Thick shake blended with Oreo cookies.', 219, NULL, 'https://images.pexels.com/photos/11512980/pexels-photo-11512980.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Oreo cookie milk shake', 'veg', NULL, false, false, '1 glass', 13),
  ('sp-014', 'soups-shakes', 'Mango Bloom', 'Refreshing mango shake with seasonal mango pulp.', 219, NULL, 'https://images.pexels.com/photos/6174874/pexels-photo-6174874.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mango milk shake', 'veg', NULL, false, false, '1 glass', 14),
  ('sp-015', 'soups-shakes', 'Choco Brownie Shake', 'Indulgent shake with chocolate brownie chunks.', 249, NULL, 'https://images.pexels.com/photos/30660270/pexels-photo-30660270.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chocolate brownie shake', 'veg', NULL, false, true, '1 glass', 15),
  ('sp-016', 'soups-shakes', 'Popular Freak Shake', 'Over-the-top freak shake with brownie, ice cream, and toppings.', 309, NULL, 'https://images.pexels.com/photos/5041474/pexels-photo-5041474.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Freak shake with brownie and ice cream toppings', 'veg', NULL, true, true, '1 glass', 16),
  ('qb-001', 'quick-bites', 'Classic Salted French Fries', 'Golden crispy fries sprinkled with salt.', 199, NULL, 'https://images.pexels.com/photos/115740/pexels-photo-115740.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Salted french fries with ketchup', 'veg', NULL, true, false, '1 plate', 1),
  ('qb-002', 'quick-bites', 'Crunchy Onion Pakoda', 'Crispy onion fritters deep-fried to golden perfection.', 169, NULL, 'https://images.pexels.com/photos/33104648/pexels-photo-33104648.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Onion pakoda fritters', 'veg', NULL, false, false, '1 plate', 2),
  ('qb-003', 'quick-bites', 'Golden Paneer Pakoda', 'Cottage cheese fritters with a crispy coating.', 239, NULL, 'https://images.pexels.com/photos/33104648/pexels-photo-33104648.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer pakoda fritters', 'veg', NULL, false, false, '1 plate', 3),
  ('qb-004', 'quick-bites', 'Crispy Chicken Pakoda', 'Spiced chicken fritters, crunchy outside and juicy inside.', 329, NULL, 'https://images.pexels.com/photos/33104648/pexels-photo-33104648.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken pakoda fritters', 'non-veg', 'medium', false, false, '1 plate', 4),
  ('qb-005', 'quick-bites', 'Creamy Veg Mayo Sandwich', 'Vegetable sandwich with creamy mayo dressing.', 199, NULL, 'https://images.pexels.com/photos/39195756/pexels-photo-39195756.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg mayo sandwich with fries', 'veg', NULL, false, false, '1 plate', 5),
  ('qb-006', 'quick-bites', 'Bombay Style Veg Sandwich', 'Classic Mumbai street-style vegetable sandwich.', 199, NULL, 'https://images.pexels.com/photos/39195756/pexels-photo-39195756.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Bombay style veg sandwich', 'veg', NULL, false, false, '1 plate', 6),
  ('qb-007', 'quick-bites', 'Crunchy Veg Spring Roll', 'Crispy spring rolls stuffed with seasoned vegetables.', 219, NULL, 'https://images.pexels.com/photos/29037269/pexels-photo-29037269.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Crispy vegetable spring rolls', 'veg', NULL, false, false, '1 plate', 7),
  ('qb-008', 'quick-bites', 'Cheesy Paneer Spring Roll', 'Spring rolls filled with paneer and melted cheese.', 229, NULL, 'https://images.pexels.com/photos/29037269/pexels-photo-29037269.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer cheese spring rolls', 'veg', NULL, false, false, '1 plate', 8),
  ('qb-009', 'quick-bites', 'Crispy Chicken Spring Roll', 'Golden spring rolls stuffed with spiced chicken.', 259, NULL, 'https://images.pexels.com/photos/29037269/pexels-photo-29037269.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken spring rolls', 'non-veg', 'medium', false, false, '1 plate', 9),
  ('qb-010', 'quick-bites', 'Crispy Veg Kathi Roll', 'Vegetable-filled Kathi roll wrapped in flaky paratha.', 199, NULL, 'https://images.pexels.com/photos/5713744/pexels-photo-5713744.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg kathi roll wrap', 'veg', NULL, false, false, '1 roll', 10),
  ('qb-011', 'quick-bites', 'Street Style Egg Kathi Roll', 'Egg-filled Kathi roll with onions and spices.', 209, NULL, 'https://images.pexels.com/photos/5713744/pexels-photo-5713744.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Egg kathi roll wrap', 'egg', NULL, false, false, '1 roll', 11),
  ('qb-012', 'quick-bites', 'Popular Spl. Chicken Kathi Roll', 'Our special chicken Kathi roll with signature masala.', 219, NULL, 'https://images.pexels.com/photos/5713744/pexels-photo-5713744.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken kathi roll wrap', 'non-veg', 'medium', true, false, '1 roll', 12),
  ('qb-013', 'quick-bites', 'Special Pav Bhaji', 'Buttery mashed vegetable curry served with toasted pav.', 209, NULL, 'https://images.pexels.com/photos/166654/pexels-photo-166654.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Pav bhaji with buttered buns', 'veg', NULL, true, false, '1 plate', 13),
  ('ic-001', 'indo-chinese', 'Classic Veg Manchurian (Dry/Gravy)', 'Veg Manchurian balls in tangy sauce — dry or gravy.', 259, NULL, 'https://images.pexels.com/photos/29631489/pexels-photo-29631489.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg Manchurian balls with sauce', 'veg', 'medium', false, false, '1 plate', 1),
  ('ic-002', 'indo-chinese', 'Sweet & Spicy Honey Chilli Potato', 'Crispy potato tossed in honey chilli sauce.', 220, NULL, 'https://images.pexels.com/photos/11485199/pexels-photo-11485199.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Honey chilli potato with sauce', 'veg', 'medium', true, false, '1 plate', 2),
  ('ic-003', 'indo-chinese', 'Spicy Chilli Paneer (Dry/Gravy)', 'Paneer cubes tossed in spicy chilli sauce.', 350, NULL, 'https://images.pexels.com/photos/29631468/pexels-photo-29631468.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chilli paneer in sauce', 'veg', 'hot', false, false, '1 plate', 3),
  ('ic-004', 'indo-chinese', 'Paneer 65', 'Crispy spiced paneer bites with curry leaves.', 324, NULL, 'https://images.pexels.com/photos/29631468/pexels-photo-29631468.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer 65 crispy bites', 'veg', 'hot', false, false, '1 plate', 4),
  ('ic-005', 'indo-chinese', 'Zesty Paneer Manchurian Dry', 'Paneer Manchurian tossed in a zesty dry sauce.', 324, NULL, 'https://images.pexels.com/photos/29631489/pexels-photo-29631489.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer Manchurian dry', 'veg', 'medium', false, false, '1 plate', 5),
  ('ic-006', 'indo-chinese', 'Crispy Paneer Salt & Pepper', 'Crispy paneer tossed with salt, pepper, and herbs.', 350, NULL, 'https://images.pexels.com/photos/29631468/pexels-photo-29631468.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer salt and pepper', 'veg', NULL, false, false, '1 plate', 6),
  ('ic-007', 'indo-chinese', 'Hot Garlic Tossed Paneer', 'Paneer tossed in a fiery hot garlic sauce.', 363, NULL, 'https://images.pexels.com/photos/29631468/pexels-photo-29631468.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Hot garlic paneer', 'veg', 'hot', false, false, '1 plate', 7),
  ('ic-008', 'indo-chinese', 'Spicy Chilli Mushroom', 'Mushrooms tossed in spicy chilli sauce.', 324, NULL, 'https://images.pexels.com/photos/30546532/pexels-photo-30546532.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chilli mushroom', 'veg', 'hot', false, false, '1 plate', 8),
  ('ic-009', 'indo-chinese', 'Crispy Fried Mushroom', 'Golden crispy fried mushrooms with herbs.', 324, NULL, 'https://images.pexels.com/photos/13065199/pexels-photo-13065199.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Crispy fried mushrooms', 'veg', NULL, false, false, '1 plate', 9),
  ('ic-010', 'indo-chinese', 'Chilli Tossed Baby Corn', 'Baby corn tossed in spicy chilli sauce.', 311, NULL, 'https://images.pexels.com/photos/34203235/pexels-photo-34203235.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chilli baby corn', 'veg', 'medium', false, false, '1 plate', 10),
  ('ic-011', 'indo-chinese', 'Baby Corn Salt & Pepper', 'Crispy baby corn with salt, pepper, and herbs.', 311, NULL, 'https://images.pexels.com/photos/34203235/pexels-photo-34203235.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Baby corn salt and pepper', 'veg', NULL, false, false, '1 plate', 11),
  ('ic-012', 'indo-chinese', 'Veggies Macaroni Pasta', 'Macaroni tossed with vegetables and spices.', 233, NULL, 'https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Vegetable macaroni pasta', 'veg', NULL, false, false, '1 plate', 12),
  ('ic-013', 'indo-chinese', 'Creamy Macaroni Pasta', 'Macaroni in a rich and creamy white sauce.', 311, NULL, 'https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Creamy macaroni pasta', 'veg', NULL, false, false, '1 plate', 13),
  ('ic-014', 'indo-chinese', 'Vegetable Masala Maggi', 'Instant noodles tossed with vegetables and masala.', 207, NULL, 'https://images.pexels.com/photos/4635600/pexels-photo-4635600.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Vegetable masala Maggi noodles', 'veg', NULL, true, false, '1 plate', 14),
  ('ic-015', 'indo-chinese', 'Classic Chilli Pasta', 'Pasta tossed in a spicy chilli sauce with veggies.', 259, NULL, 'https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chilli pasta with vegetables', 'veg', 'medium', false, false, '1 plate', 15),
  ('ic-016', 'indo-chinese', 'Popular''s Signature Chilli Chicken', 'Our signature chilli chicken with a fiery sauce.', 363, NULL, 'https://images.pexels.com/photos/18698224/pexels-photo-18698224.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chilli chicken with peppers', 'non-veg', 'hot', true, true, '1 plate', 16),
  ('ic-017', 'indo-chinese', 'Chef''s Special Drums of Heaven', 'Crispy chicken drumettes tossed in a sweet-spicy glaze.', 415, NULL, 'https://images.pexels.com/photos/29631422/pexels-photo-29631422.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Drums of heaven chicken', 'non-veg', 'medium', false, true, '1 plate', 17),
  ('ic-018', 'indo-chinese', 'Chicken 65', 'Spicy deep-fried chicken with curry leaves.', 363, NULL, 'https://images.pexels.com/photos/5946434/pexels-photo-5946434.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken 65 fried bites', 'non-veg', 'hot', false, false, '1 plate', 18),
  ('ic-019', 'indo-chinese', 'Classic Chicken Manchurian', 'Chicken Manchurian in a tangy Indo-Chinese gravy.', 350, NULL, 'https://images.pexels.com/photos/29631489/pexels-photo-29631489.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken Manchurian with sauce', 'non-veg', 'medium', false, false, '1 plate', 19),
  ('ic-020', 'indo-chinese', 'Fiery Hot Garlic Chicken', 'Chicken tossed in a fiery hot garlic sauce.', 350, NULL, 'https://images.pexels.com/photos/18698224/pexels-photo-18698224.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Hot garlic chicken', 'non-veg', 'hot', false, false, '1 plate', 20),
  ('ic-021', 'indo-chinese', 'Chicken Salt & Pepper', 'Crispy chicken tossed with salt, pepper, and herbs.', 337, NULL, 'https://images.pexels.com/photos/5652266/pexels-photo-5652266.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken salt and pepper', 'non-veg', NULL, false, false, '1 plate', 21),
  ('ic-022', 'indo-chinese', 'Extra Crispy Fried Chicken', 'Double-fried chicken with an extra crunchy coating.', 337, NULL, 'https://images.pexels.com/photos/5652266/pexels-photo-5652266.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Extra crispy fried chicken', 'non-veg', NULL, false, false, '1 plate', 22),
  ('tv-001', 'tandoor-veg', 'Smoky Paneer Tikka', 'Cottage cheese marinated in spiced yogurt, char-grilled in the tandoor.', 279, NULL, 'https://images.pexels.com/photos/3928854/pexels-photo-3928854.png?auto=compress&cs=tinysrgb&h=400&w=400', 'Smoky paneer tikka skewers', 'veg', 'medium', true, false, '1 plate', 1),
  ('tv-002', 'tandoor-veg', 'Chatpata Achari Paneer Tikka', 'Paneer marinated in tangy pickle spices and grilled.', 289, NULL, 'https://images.pexels.com/photos/3928854/pexels-photo-3928854.png?auto=compress&cs=tinysrgb&h=400&w=400', 'Achari paneer tikka', 'veg', 'medium', false, false, '1 plate', 2),
  ('tv-003', 'tandoor-veg', 'Spicy Kalimirch Paneer Tikka', 'Paneer tikka with a bold black pepper marinade.', 299, NULL, 'https://images.pexels.com/photos/3928854/pexels-photo-3928854.png?auto=compress&cs=tinysrgb&h=400&w=400', 'Kalimirch paneer tikka', 'veg', 'hot', false, false, '1 plate', 3),
  ('tv-004', 'tandoor-veg', 'Creamy Paneer Malai Tikka', 'Soft paneer marinated in cream and mild spices.', 339, NULL, 'https://images.pexels.com/photos/29173105/pexels-photo-29173105.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer malai tikka', 'veg', NULL, false, false, '1 plate', 4),
  ('tv-005', 'tandoor-veg', 'Char-Grilled Paneer Seekh Kabab', 'Paneer seekh kababs grilled in the tandoor.', 329, NULL, 'https://images.pexels.com/photos/29173105/pexels-photo-29173105.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer seekh kabab', 'veg', 'medium', false, false, '1 plate', 5),
  ('tv-006', 'tandoor-veg', 'Melt-in-mouth Paneer Malai Seekh', 'Soft and creamy paneer malai seekh kababs.', 339, NULL, 'https://images.pexels.com/photos/29173105/pexels-photo-29173105.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer malai seekh kabab', 'veg', NULL, false, false, '1 plate', 6),
  ('tv-007', 'tandoor-veg', 'Classic Tandoori Mushroom', 'Mushrooms marinated in tandoori spices and grilled.', 289, NULL, 'https://images.pexels.com/photos/6646154/pexels-photo-6646154.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Tandoori mushrooms', 'veg', 'medium', false, false, '1 plate', 7),
  ('tv-008', 'tandoor-veg', 'Pepper-Spiced Mushroom Tikka', 'Mushroom tikka with a peppery marinade.', 289, NULL, 'https://images.pexels.com/photos/6646154/pexels-photo-6646154.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mushroom tikka with pepper', 'veg', 'medium', false, false, '1 plate', 8),
  ('tv-009', 'tandoor-veg', 'Rich Mushroom Malai Tikka', 'Creamy mushroom tikka with a malai marinade.', 309, NULL, 'https://images.pexels.com/photos/34429561/pexels-photo-34429561.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mushroom malai tikka', 'veg', NULL, false, false, '1 plate', 9),
  ('tv-010', 'tandoor-veg', 'Crispy Hara Bhara Kabab', 'Spinach and pea patties, crispy outside and soft inside.', 289, NULL, 'https://images.pexels.com/photos/6853406/pexels-photo-6853406.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Hara bhara kabab', 'veg', NULL, false, false, '1 plate', 10),
  ('tv-011', 'tandoor-veg', 'Signature Dahi Ke Kabab', 'Hung curd kababs with a melt-in-mouth texture.', 309, NULL, 'https://images.pexels.com/photos/26245461/pexels-photo-26245461.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Dahi ke kabab', 'veg', NULL, false, true, '1 plate', 11),
  ('tv-012', 'tandoor-veg', 'Popular''s Spl. Veg Seekh', 'Our special vegetable seekh kababs grilled in the tandoor.', 289, NULL, 'https://images.pexels.com/photos/6853406/pexels-photo-6853406.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg seekh kabab', 'veg', 'medium', false, false, '1 plate', 12),
  ('tv-013', 'tandoor-veg', 'Rich Veg Malai Seekh Kabab', 'Creamy vegetable seekh kababs with a malai glaze.', 309, NULL, 'https://images.pexels.com/photos/6853406/pexels-photo-6853406.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg malai seekh kabab', 'veg', NULL, false, false, '1 plate', 13),
  ('tv-014', 'tandoor-veg', 'Char-Roasted Aloo Gobhi', 'Potatoes and cauliflower roasted in the tandoor.', 219, NULL, 'https://images.pexels.com/photos/6853406/pexels-photo-6853406.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Char-roasted aloo gobhi', 'veg', 'mild', false, false, '1 plate', 14),
  ('tn-001', 'tandoor-nonveg', 'Signature Tandoori Chicken (H/F)', 'Half / Full — classic tandoori chicken marinated in yogurt and spices.', 369, 649, 'https://images.pexels.com/photos/36895285/pexels-photo-36895285.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Tandoori chicken with lime', 'non-veg', 'medium', true, false, 'Half / Full', 1),
  ('tn-002', 'tandoor-nonveg', 'Creamy Afghani Tandoori Chicken (H/F)', 'Half / Full — chicken in a creamy Afghani marinade, char-grilled.', 389, 679, 'https://images.pexels.com/photos/29685054/pexels-photo-29685054.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Afghani tandoori chicken', 'non-veg', NULL, false, false, 'Half / Full', 2),
  ('tn-003', 'tandoor-nonveg', 'Smokey Chicken Tikka', 'Boneless chicken marinated in spices and char-grilled.', 349, NULL, 'https://images.pexels.com/photos/16423838/pexels-photo-16423838.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken tikka skewers', 'non-veg', 'medium', true, false, '1 plate', 3),
  ('tn-004', 'tandoor-nonveg', 'Tangy Achari Chicken Tikka', 'Chicken tikka with a tangy pickle-spice marinade.', 349, NULL, 'https://images.pexels.com/photos/16423838/pexels-photo-16423838.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Achari chicken tikka', 'non-veg', 'medium', false, false, '1 plate', 4),
  ('tn-005', 'tandoor-nonveg', 'Green Chicken Tikka', 'Chicken tikka marinated in a fresh green herb paste.', 349, NULL, 'https://images.pexels.com/photos/16423838/pexels-photo-16423838.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Green chicken tikka', 'non-veg', 'mild', false, false, '1 plate', 5),
  ('tn-006', 'tandoor-nonveg', 'Fiery Chicken Angara Tikka', 'Spicy chicken tikka with a smoky fiery marinade.', 349, NULL, 'https://images.pexels.com/photos/16423838/pexels-photo-16423838.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken angara tikka', 'non-veg', 'hot', false, false, '1 plate', 6),
  ('tn-007', 'tandoor-nonveg', 'Pepper-crusted Chicken Kalimirch Tikka', 'Chicken tikka with a bold black pepper crust.', 369, NULL, 'https://images.pexels.com/photos/16423838/pexels-photo-16423838.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken kalimirch tikka', 'non-veg', 'hot', false, false, '1 plate', 7),
  ('tn-008', 'tandoor-nonveg', 'Silky Chicken Malai Tikka', 'Soft chicken tikka in a creamy malai marinade.', 369, NULL, 'https://images.pexels.com/photos/18877581/pexels-photo-18877581.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken malai tikka', 'non-veg', NULL, false, false, '1 plate', 8),
  ('tn-009', 'tandoor-nonveg', 'Nawabi Chicken Reshmi Tikka', 'Silky chicken tikka with a royal Nawabi marinade.', 369, NULL, 'https://images.pexels.com/photos/16423838/pexels-photo-16423838.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken reshmi tikka', 'non-veg', NULL, false, false, '1 plate', 9),
  ('tn-010', 'tandoor-nonveg', 'Kalimirch Afghani Chicken', 'Afghani chicken with a black pepper twist.', 389, NULL, 'https://images.pexels.com/photos/36895285/pexels-photo-36895285.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Kalimirch Afghani chicken', 'non-veg', 'medium', false, false, '1 plate', 10),
  ('tn-011', 'tandoor-nonveg', 'Juicy Chicken Seekh Kabab', 'Minced chicken seekh kababs grilled in the tandoor.', 349, NULL, 'https://images.pexels.com/photos/9646858/pexels-photo-9646858.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken seekh kabab skewers', 'non-veg', 'medium', false, false, '1 plate', 11),
  ('tn-012', 'tandoor-nonveg', 'Royal Afghani Seekh Kabab', 'Afghani-style seekh kabab with a creamy marinade.', 369, NULL, 'https://images.pexels.com/photos/9646858/pexels-photo-9646858.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Afghani seekh kabab', 'non-veg', NULL, false, false, '1 plate', 12),
  ('tn-013', 'tandoor-nonveg', 'Dineout Spl. Mutton Seekh Kabab', 'Premium mutton seekh kabab with our special masala.', 519, NULL, 'https://images.pexels.com/photos/18698226/pexels-photo-18698226.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mutton seekh kabab', 'non-veg', 'medium', false, true, '1 plate', 13),
  ('vm-001', 'veg-main', 'Creamy Paneer Butter Masala', 'Cottage cheese in a rich tomato and butter gravy.', 349, NULL, 'https://images.pexels.com/photos/29685056/pexels-photo-29685056.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer butter masala', 'veg', 'mild', true, false, '1 bowl', 1),
  ('vm-002', 'veg-main', 'Traditional Kadhai Paneer', 'Paneer cooked with bell peppers in a kadhai masala.', 369, NULL, 'https://images.pexels.com/photos/29631461/pexels-photo-29631461.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Kadhai paneer with bell peppers', 'veg', 'medium', false, false, '1 bowl', 2),
  ('vm-003', 'veg-main', 'Sahi Paneer Royal', 'Royal paneer curry in a rich and creamy gravy.', 369, NULL, 'https://images.pexels.com/photos/29685056/pexels-photo-29685056.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Sahi paneer royal', 'veg', 'mild', false, false, '1 bowl', 3),
  ('vm-004', 'veg-main', 'Luscious Paneer Lababdar', 'Paneer in a luscious gravy with cream and spices.', 389, NULL, 'https://images.pexels.com/photos/29631461/pexels-photo-29631461.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer lababdar', 'veg', 'mild', false, false, '1 bowl', 4),
  ('vm-005', 'veg-main', 'Char-Grilled Paneer Tikka Masala', 'Tandoori paneer tikka simmered in a spiced gravy.', 339, NULL, 'https://images.pexels.com/photos/30858402/pexels-photo-30858402.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer tikka masala', 'veg', 'medium', false, false, '1 bowl', 5),
  ('vm-006', 'veg-main', 'Popular''s Special Paneer Punjabi', 'Our signature Punjabi-style paneer curry.', 379, NULL, 'https://images.pexels.com/photos/29631461/pexels-photo-29631461.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer Punjabi special', 'veg', 'medium', true, false, '1 bowl', 6),
  ('vm-007', 'veg-main', 'Spicy Paneer Kolhapuri', 'Fiery Kolhapuri-style paneer with bold spices.', 379, NULL, 'https://images.pexels.com/photos/29631461/pexels-photo-29631461.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer Kolhapuri', 'veg', 'hot', false, false, '1 bowl', 7),
  ('vm-008', 'veg-main', 'Authentic Paneer Handi', 'Paneer slow-cooked in a traditional handi.', 329, NULL, 'https://images.pexels.com/photos/29685056/pexels-photo-29685056.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer handi', 'veg', 'medium', false, false, '1 bowl', 8),
  ('vm-009', 'veg-main', 'Rich Paneer Do Pyaza', 'Paneer curry with generous onions and rich gravy.', 329, NULL, 'https://images.pexels.com/photos/29631461/pexels-photo-29631461.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer do pyaza', 'veg', 'mild', false, false, '1 bowl', 9),
  ('vm-010', 'veg-main', 'Classic Paneer Mutter Masala', 'Paneer and green peas in a classic masala gravy.', 339, NULL, 'https://images.pexels.com/photos/29631461/pexels-photo-29631461.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer mutter masala', 'veg', 'mild', false, false, '1 bowl', 10),
  ('vm-011', 'veg-main', 'Melt-in-Mouth Paneer Kofta', 'Soft paneer kofta balls in a rich gravy.', 339, NULL, 'https://images.pexels.com/photos/29685056/pexels-photo-29685056.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer kofta in gravy', 'veg', 'mild', false, false, '1 bowl', 11),
  ('vm-012', 'veg-main', 'Rich Veg Malai Kofta', 'Vegetable kofta in a creamy malai gravy.', 309, NULL, 'https://images.pexels.com/photos/29685056/pexels-photo-29685056.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg malai kofta', 'veg', 'mild', false, false, '1 bowl', 12),
  ('vm-013', 'veg-main', 'Creamy Mushroom Butter Masala', 'Mushrooms in a rich butter and tomato gravy.', 329, NULL, 'https://images.pexels.com/photos/35041649/pexels-photo-35041649.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mushroom butter masala', 'veg', 'mild', false, false, '1 bowl', 13),
  ('vm-014', 'veg-main', 'Smoky Mushroom Tikka Masala', 'Tandoori mushroom tikka in a spiced gravy.', 329, NULL, 'https://images.pexels.com/photos/35041649/pexels-photo-35041649.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mushroom tikka masala', 'veg', 'medium', false, false, '1 bowl', 14),
  ('vm-015', 'veg-main', 'Fresh Mushroom Mutter Masala', 'Mushrooms and green peas in a flavorful masala.', 299, NULL, 'https://images.pexels.com/photos/35041649/pexels-photo-35041649.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mushroom mutter masala', 'veg', 'mild', false, false, '1 bowl', 15),
  ('vm-016', 'veg-main', 'Rich Mushroom Do Pyaza', 'Mushroom curry with double the onions.', 299, NULL, 'https://images.pexels.com/photos/35041649/pexels-photo-35041649.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mushroom do pyaza', 'veg', 'mild', false, false, '1 bowl', 16),
  ('vm-017', 'veg-main', 'Baby Corn Mushroom Masala', 'Baby corn and mushrooms in a spiced gravy.', 329, NULL, 'https://images.pexels.com/photos/35041649/pexels-photo-35041649.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Baby corn mushroom masala', 'veg', 'medium', false, false, '1 bowl', 17),
  ('vm-018', 'veg-main', 'Slow-Cooked Mix Veg Handi', 'Seasonal vegetables slow-cooked in a handi.', 259, NULL, 'https://images.pexels.com/photos/35267281/pexels-photo-35267281.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mix veg handi', 'veg', 'mild', false, false, '1 bowl', 18),
  ('vm-019', 'veg-main', 'Homestyle Bhindi Do Pyaza', 'Okra cooked with onions in a homestyle masala.', 209, NULL, 'https://images.pexels.com/photos/33643313/pexels-photo-33643313.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Bhindi do pyaza', 'veg', 'mild', false, false, '1 bowl', 19),
  ('vm-020', 'veg-main', 'Traditional Aloo Dum', 'Potatoes in a traditional spicy dum masala.', 209, NULL, 'https://images.pexels.com/photos/19781596/pexels-photo-19781596.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Aloo dum masala', 'veg', 'medium', false, false, '1 bowl', 20),
  ('vm-021', 'veg-main', 'Classic Aloo Gobhi Masala', 'Potatoes and cauliflower in a classic masala.', 219, NULL, 'https://images.pexels.com/photos/19781596/pexels-photo-19781596.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Aloo gobhi masala', 'veg', 'mild', false, false, '1 bowl', 21),
  ('vm-022', 'veg-main', 'Punjabi Chole Masala', 'Punjabi-style chickpeas in a robust masala gravy.', 209, NULL, 'https://images.pexels.com/photos/17223838/pexels-photo-17223838.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Punjabi chole masala', 'veg', 'medium', false, false, '1 bowl', 22),
  ('nv-001', 'nonveg-main', 'Patna''s Spl. Chicken Ahunna', '1kg — Patna’s signature chicken Ahunna, slow-cooked with rich spices.', 1299, NULL, 'https://images.pexels.com/photos/29684988/pexels-photo-29684988.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken Ahunna curry', 'non-veg', 'medium', false, true, '1kg', 1),
  ('nv-002', 'nonveg-main', 'Signature Chicken Dehati', '8pcs — rustic village-style chicken curry with bold spices.', 809, NULL, 'https://images.pexels.com/photos/29684987/pexels-photo-29684987.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken dehati curry', 'non-veg', 'hot', false, false, '8 pieces', 2),
  ('nv-003', 'nonveg-main', 'Classic Butter Chicken Masala', '4pcs — tandoori chicken in a rich tomato and butter gravy.', 419, NULL, 'https://images.pexels.com/photos/29685054/pexels-photo-29685054.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Butter chicken masala', 'non-veg', 'mild', true, false, '4 pieces', 3),
  ('nv-004', 'nonveg-main', 'Smoky Chicken Tikka Masala', '4pcs — char-grilled chicken tikka in a spiced gravy.', 399, NULL, 'https://images.pexels.com/photos/29685054/pexels-photo-29685054.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken tikka masala', 'non-veg', 'medium', false, false, '4 pieces', 4),
  ('nv-005', 'nonveg-main', 'Authentic Chicken Handi', '4pcs — chicken slow-cooked in a traditional handi.', 389, NULL, 'https://images.pexels.com/photos/29684987/pexels-photo-29684987.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken handi curry', 'non-veg', 'medium', false, false, '4 pieces', 5),
  ('nv-006', 'nonveg-main', 'Fiery Chicken Kolhapuri', '4pcs — bold Kolhapuri-style spicy chicken curry.', 389, NULL, 'https://images.pexels.com/photos/29684987/pexels-photo-29684987.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken Kolhapuri', 'non-veg', 'hot', false, false, '4 pieces', 6),
  ('nv-007', 'nonveg-main', 'Bengal Style Chicken Kassa', '4pcs — Bengali-style chicken in a thick roasted masala.', 389, NULL, 'https://images.pexels.com/photos/29684987/pexels-photo-29684987.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken kassa', 'non-veg', 'medium', false, false, '4 pieces', 7),
  ('nv-008', 'nonveg-main', 'Chicken Do Pyaza', '4pcs — chicken curry with generous onions and rich gravy.', 379, NULL, 'https://images.pexels.com/photos/29684987/pexels-photo-29684987.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken do pyaza', 'non-veg', 'mild', false, false, '4 pieces', 8),
  ('nv-009', 'nonveg-main', 'Slow-Cooked Chicken Istu', '4pcs — homestyle chicken stew slow-cooked with spices.', 389, NULL, 'https://images.pexels.com/photos/29684987/pexels-photo-29684987.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken istu stew', 'non-veg', 'mild', false, false, '4 pieces', 9),
  ('nv-010', 'nonveg-main', 'Homestyle Chicken Curry', '2pcs — classic homestyle chicken curry with aromatic spices.', 199, NULL, 'https://images.pexels.com/photos/29684987/pexels-photo-29684987.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Homestyle chicken curry', 'non-veg', 'medium', true, false, '2 pieces', 10),
  ('nv-011', 'nonveg-main', 'Rich Chicken Masala', '2pcs — chicken in a rich and flavorful masala gravy.', 199, NULL, 'https://images.pexels.com/photos/29684987/pexels-photo-29684987.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken masala', 'non-veg', 'medium', false, false, '2 pieces', 11),
  ('nv-012', 'nonveg-main', 'Rich Mutton Rogan Josh', '4pcs — Kashmiri-style mutton in a rich red gravy.', 509, NULL, 'https://images.pexels.com/photos/28674690/pexels-photo-28674690.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mutton rogan josh', 'non-veg', 'medium', true, false, '4 pieces', 12),
  ('nv-013', 'nonveg-main', 'Tender Mutton Do Pyaza', '4pcs — mutton curry with double the onions.', 509, NULL, 'https://images.pexels.com/photos/28674690/pexels-photo-28674690.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mutton do pyaza', 'non-veg', 'medium', false, false, '4 pieces', 13),
  ('nv-014', 'nonveg-main', 'Slow-Cooked Mutton Handi', '4pcs — mutton slow-cooked in a traditional handi.', 509, NULL, 'https://images.pexels.com/photos/28674690/pexels-photo-28674690.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mutton handi curry', 'non-veg', 'medium', false, false, '4 pieces', 14),
  ('nv-015', 'nonveg-main', 'Spicy Homestyle Egg Curry', '4pcs — boiled eggs in a spicy homestyle masala gravy.', 219, NULL, 'https://images.pexels.com/photos/35071817/pexels-photo-35071817.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Spicy egg curry', 'egg', 'hot', false, false, '4 pieces', 15),
  ('nv-016', 'nonveg-main', 'Dhaba Style Egg Masala', '2pcs — dhaba-style egg curry with a rustic masala.', 179, NULL, 'https://images.pexels.com/photos/35071817/pexels-photo-35071817.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Dhaba style egg masala', 'egg', 'medium', false, false, '2 pieces', 16),
  ('bd-001', 'breads', 'Soft Tawa Roti', 'Whole wheat flatbread cooked on a tawa.', 29, NULL, 'https://images.pexels.com/photos/28674556/pexels-photo-28674556.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Tawa roti', 'veg', NULL, false, false, '1 piece', 1),
  ('bd-002', 'breads', 'Traditional Tandoori Roti', 'Whole wheat bread baked in the clay tandoor.', 39, NULL, 'https://images.pexels.com/photos/28674556/pexels-photo-28674556.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Tandoori roti', 'veg', NULL, false, false, '1 piece', 2),
  ('bd-003', 'breads', 'Butter Tandoori Roti', 'Tandoori roti brushed with fresh butter.', 49, NULL, 'https://images.pexels.com/photos/28674556/pexels-photo-28674556.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Butter tandoori roti', 'veg', NULL, false, false, '1 piece', 3),
  ('bd-004', 'breads', 'Soft Plain Naan', 'Leavened bread baked in the tandoor.', 59, NULL, 'https://images.pexels.com/photos/30203311/pexels-photo-30203311.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Plain naan', 'veg', NULL, false, false, '1 piece', 4),
  ('bd-005', 'breads', 'Rich Butter Naan', 'Naan brushed generously with butter.', 79, NULL, 'https://images.pexels.com/photos/30203311/pexels-photo-30203311.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Butter naan', 'veg', NULL, true, false, '1 piece', 5),
  ('bd-006', 'breads', 'Roasted Garlic Butter Naan', 'Naan topped with roasted garlic and butter.', 89, NULL, 'https://images.pexels.com/photos/10337726/pexels-photo-10337726.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Garlic butter naan', 'veg', NULL, false, false, '1 piece', 6),
  ('bd-007', 'breads', 'Flaky Laccha Paratha', 'Multi-layered flaky paratha, crispy and buttery.', 89, NULL, 'https://images.pexels.com/photos/37555450/pexels-photo-37555450.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Laccha paratha', 'veg', NULL, false, false, '1 piece', 7),
  ('bd-008', 'breads', 'Onion Stuffed Kulcha', 'Kulcha stuffed with spiced onion filling.', 89, NULL, 'https://images.pexels.com/photos/6183640/pexels-photo-6183640.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Onion stuffed kulcha', 'veg', NULL, false, false, '1 piece', 8),
  ('bd-009', 'breads', 'Premium Paneer Stuffed Kulcha', 'Kulcha stuffed with a rich paneer filling.', 99, NULL, 'https://images.pexels.com/photos/6183640/pexels-photo-6183640.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer stuffed kulcha', 'veg', NULL, false, false, '1 piece', 9),
  ('bd-010', 'breads', 'Rich Paneer Stuffed Paratha', 'Paratha stuffed with spiced paneer, served with butter.', 109, NULL, 'https://images.pexels.com/photos/37555450/pexels-photo-37555450.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer stuffed paratha', 'veg', NULL, false, false, '1 piece', 10),
  ('bd-011', 'breads', 'Chicken Keema Stuffed Butter Naan', 'Naan stuffed with spiced chicken keema and butter.', 129, NULL, 'https://images.pexels.com/photos/32986478/pexels-photo-32986478.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken keema stuffed naan', 'non-veg', 'medium', false, false, '1 piece', 11),
  ('sr-001', 'salad-raita', 'Farm Fresh Green Salad', 'Fresh cucumber, tomato, onion, and lemon.', 99, NULL, 'https://images.pexels.com/photos/842545/pexels-photo-842545.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Fresh green salad with vegetables', 'veg', NULL, false, false, '1 plate', 1),
  ('sr-002', 'salad-raita', 'Fire-Roasted Papad (2pcs)', 'Papad roasted over an open flame.', 69, NULL, 'https://images.pexels.com/photos/4887993/pexels-photo-4887993.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Roasted papad', 'veg', NULL, false, false, '2 pieces', 2),
  ('sr-003', 'salad-raita', 'Crispy Fried Papad (2pcs)', 'Papad deep-fried to crispy perfection.', 79, NULL, 'https://images.pexels.com/photos/4887993/pexels-photo-4887993.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Fried papad', 'veg', NULL, false, false, '2 pieces', 3),
  ('sr-004', 'salad-raita', 'Chatpata Masala Papad (2pcs)', 'Papad topped with chatpata masala and chutney.', 89, NULL, 'https://images.pexels.com/photos/34270742/pexels-photo-34270742.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Masala papad with toppings', 'veg', NULL, false, false, '2 pieces', 4),
  ('sr-005', 'salad-raita', 'Spicy Masala Peanut', 'Roasted peanuts tossed with spicy masala.', 89, NULL, 'https://images.pexels.com/photos/4887993/pexels-photo-4887993.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Masala peanuts', 'veg', 'medium', false, false, '1 bowl', 5),
  ('sr-006', 'salad-raita', 'Chilled Boondi Raita', 'Yogurt with soft boondi and spices.', 109, NULL, 'https://images.pexels.com/photos/29699511/pexels-photo-29699511.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Boondi raita in a bowl', 'veg', NULL, false, false, '1 bowl', 6),
  ('sr-007', 'salad-raita', 'Garden Fresh Mix Veg Raita', 'Yogurt with fresh chopped vegetables and spices.', 129, NULL, 'https://images.pexels.com/photos/29699511/pexels-photo-29699511.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mix veg raita', 'veg', NULL, false, false, '1 bowl', 7),
  ('sr-008', 'salad-raita', 'Cooling Kheera Raita', 'Yogurt with grated cucumber and cumin.', 89, NULL, 'https://images.pexels.com/photos/29699511/pexels-photo-29699511.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Kheera raita', 'veg', NULL, false, false, '1 bowl', 8),
  ('sr-009', 'salad-raita', 'Refreshing Poodina Raita', 'Yogurt with fresh mint and spices.', 89, NULL, 'https://images.pexels.com/photos/29699511/pexels-photo-29699511.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Poodina mint raita', 'veg', NULL, false, false, '1 bowl', 9),
  ('ds-001', 'desserts', 'Warm Gulab Jamun (2pcs)', 'Warm milk-solid dumplings soaked in rose-flavored syrup.', 79, NULL, 'https://images.pexels.com/photos/11887844/pexels-photo-11887844.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Gulab jamun in syrup', 'veg', NULL, true, false, '2 pieces', 1),
  ('ds-002', 'desserts', 'Spongy Rasgulla (2pcs)', 'Soft spongy rasgulla in light sugar syrup.', 69, NULL, 'https://images.pexels.com/photos/37133961/pexels-photo-37133961.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Rasgulla in syrup', 'veg', NULL, false, false, '2 pieces', 2),
  ('ds-003', 'desserts', 'Rich Saffron Ras-Malai (2pcs)', 'Soft cheese patties in saffron milk with nuts.', 129, NULL, 'https://images.pexels.com/photos/14610769/pexels-photo-14610769.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Saffron ras-malai with nuts', 'veg', NULL, false, true, '2 pieces', 3),
  ('ds-004', 'desserts', 'Choice of Ice Cream', 'Pick your favourite ice cream flavour.', 69, NULL, 'https://images.pexels.com/photos/36576778/pexels-photo-36576778.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Ice cream scoop', 'veg', NULL, false, false, '1 scoop', 4),
  ('rb-001', 'rice-biryani', 'Steamed Basmati Rice', 'Fluffy steamed basmati rice, perfect with any curry.', 189, NULL, 'https://images.pexels.com/photos/35552983/pexels-photo-35552983.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Steamed basmati rice', 'veg', NULL, false, false, '1 plate', 1),
  ('rb-002', 'rice-biryani', 'Classic Jeera Rice', 'Basmati rice tempered with cumin seeds.', 199, NULL, 'https://images.pexels.com/photos/35552983/pexels-photo-35552983.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Jeera rice with cumin', 'veg', NULL, false, false, '1 plate', 2),
  ('rb-003', 'rice-biryani', 'Classic Peas Mutter Pulao', 'Basmati rice cooked with green peas and whole spices.', 219, NULL, 'https://images.pexels.com/photos/35552983/pexels-photo-35552983.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Peas pulao with basmati rice', 'veg', NULL, false, false, '1 plate', 3),
  ('rb-004', 'rice-biryani', 'Classic Veg Fried Rice', 'Rice stir-fried with vegetables and soy sauce.', 219, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg fried rice', 'veg', NULL, false, false, '1 plate', 4),
  ('rb-005', 'rice-biryani', 'Mushroom Fried Rice', 'Fried rice with mushrooms and vegetables.', 199, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mushroom fried rice', 'veg', NULL, false, false, '1 plate', 5),
  ('rb-006', 'rice-biryani', 'Spicy Schezwan Veg Fried Rice', 'Fried rice tossed in fiery Schezwan sauce.', 219, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Schezwan veg fried rice', 'veg', 'hot', false, false, '1 plate', 6),
  ('rb-007', 'rice-biryani', 'Popular''s Special Veg Fried Rice', 'Our signature veg fried rice with special masala.', 219, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Popular special veg fried rice', 'veg', NULL, true, false, '1 plate', 7),
  ('rb-008', 'rice-biryani', 'Scrambled Egg Fried Rice', 'Fried rice with scrambled eggs and vegetables.', 219, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Egg fried rice', 'egg', NULL, false, false, '1 plate', 8),
  ('rb-009', 'rice-biryani', 'Paneer Fried Rice', 'Fried rice with paneer cubes and vegetables.', 219, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer fried rice', 'veg', NULL, false, false, '1 plate', 9),
  ('rb-010', 'rice-biryani', 'Classic Chicken Fried Rice (PSP)', 'Fried rice with chicken and vegetables.', 219, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken fried rice', 'non-veg', NULL, false, false, '1 plate', 10),
  ('rb-011', 'rice-biryani', 'Fiery Schezwan Chicken Fried Rice', 'Chicken fried rice tossed in fiery Schezwan sauce.', 259, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Schezwan chicken fried rice', 'non-veg', 'hot', false, false, '1 plate', 11),
  ('rb-012', 'rice-biryani', 'Double Delight Egg & Chicken Fried Rice', 'Fried rice with both egg and chicken.', 279, NULL, 'https://images.pexels.com/photos/9045147/pexels-photo-9045147.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Egg and chicken fried rice', 'non-veg', NULL, false, false, '1 plate', 12),
  ('rb-013', 'rice-biryani', 'Shahi Veg Dum Biryani', 'Fragrant basmati with vegetables, saffron, and whole spices.', 259, NULL, 'https://images.pexels.com/photos/17696655/pexels-photo-17696655.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Shahi veg dum biryani', 'veg', NULL, false, false, '1 plate', 13),
  ('rb-014', 'rice-biryani', 'Flavorful Egg Dum Biryani', 'Dum biryani with boiled eggs and aromatic spices.', 289, NULL, 'https://images.pexels.com/photos/17696655/pexels-photo-17696655.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Egg dum biryani', 'egg', NULL, false, false, '1 plate', 14),
  ('rb-015', 'rice-biryani', 'Rich Paneer Dum Biryani', 'Dum biryani with paneer and rich masala.', 309, NULL, 'https://images.pexels.com/photos/17696655/pexels-photo-17696655.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer dum biryani', 'veg', NULL, false, false, '1 plate', 15),
  ('rb-016', 'rice-biryani', 'Nawabi Chicken Dum Biryani', 'Dum biryani with marinated chicken, saffron, and whole spices.', 329, NULL, 'https://images.pexels.com/photos/17696655/pexels-photo-17696655.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Nawabi chicken dum biryani', 'non-veg', NULL, true, true, '1 plate', 16),
  ('rb-017', 'rice-biryani', 'Dineout Mutton Dum Biryani', 'Premium mutton dum biryani with fragrant basmati and spices.', 499, NULL, 'https://images.pexels.com/photos/32986475/pexels-photo-32986475.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mutton dum biryani', 'non-veg', NULL, false, true, '1 plate', 17),
  ('rb-018', 'rice-biryani', 'Classic Yellow Dal Tadka', 'Yellow lentils tempered with cumin, garlic, and red chili.', 199, NULL, 'https://images.pexels.com/photos/37182514/pexels-photo-37182514.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Dal tadka with tempering', 'veg', NULL, false, false, '1 bowl', 18),
  ('nd-001', 'noodles', 'Veg Hakka Noodles', 'Stir-fried noodles with crunchy vegetables.', 249, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Veg Hakka noodles', 'veg', NULL, false, false, '1 plate', 1),
  ('nd-002', 'noodles', 'Desi Mix Veg Chowmein', 'Indian-style chowmein with mixed vegetables.', 239, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mix veg chowmein', 'veg', NULL, false, false, '1 plate', 2),
  ('nd-003', 'noodles', 'Spicy Schezwan Veg Noodles', 'Noodles tossed in fiery Schezwan sauce with vegetables.', 239, NULL, 'https://images.pexels.com/photos/28445827/pexels-photo-28445827.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Schezwan veg noodles', 'veg', 'hot', false, false, '1 plate', 3),
  ('nd-004', 'noodles', 'Fiery Garlic Veg Noodles', 'Noodles tossed in garlic with vegetables.', 239, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Garlic veg noodles', 'veg', 'medium', false, false, '1 plate', 4),
  ('nd-005', 'noodles', 'Paneer Hakka Noodles', 'Hakka noodles with paneer and vegetables.', 249, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Paneer Hakka noodles', 'veg', NULL, false, false, '1 plate', 5),
  ('nd-006', 'noodles', 'Mushroom Hakka Noodles', 'Hakka noodles with mushrooms and vegetables.', 249, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Mushroom Hakka noodles', 'veg', NULL, false, false, '1 plate', 6),
  ('nd-007', 'noodles', 'Popular''s Special Veg Noodles', 'Our signature veg noodles with special masala.', 259, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Popular special veg noodles', 'veg', NULL, true, false, '1 plate', 7),
  ('nd-008', 'noodles', 'Classic Chicken Hakka Noodles', 'Hakka noodles with chicken and vegetables.', 299, NULL, 'https://images.pexels.com/photos/18698263/pexels-photo-18698263.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Chicken Hakka noodles', 'non-veg', NULL, false, false, '1 plate', 8),
  ('nd-009', 'noodles', 'Schezwan Tossed Chicken Noodles', 'Chicken noodles tossed in fiery Schezwan sauce.', 289, NULL, 'https://images.pexels.com/photos/28445827/pexels-photo-28445827.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Schezwan chicken noodles', 'non-veg', 'hot', false, false, '1 plate', 9),
  ('nd-010', 'noodles', 'Hot Garlic Chicken Noodles', 'Chicken noodles tossed in a hot garlic sauce.', 289, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Hot garlic chicken noodles', 'non-veg', 'hot', false, false, '1 plate', 10),
  ('nd-011', 'noodles', 'Egg & Chicken Tossed Noodles', 'Noodles tossed with egg and chicken.', 299, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Egg and chicken noodles', 'non-veg', NULL, false, false, '1 plate', 11),
  ('nd-012', 'noodles', 'Popular''s Signature Chicken Noodles', 'Our signature chicken noodles with special masala.', 309, NULL, 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=400&w=400', 'Popular signature chicken noodles', 'non-veg', NULL, false, true, '1 plate', 12)
ON CONFLICT (id) DO NOTHING;

-- Insert 7 combo thalis
INSERT INTO combo_thalis (id, name, description, price, image, image_alt, diet, serves, items, popular, sort_order) VALUES
  ('thali-indian-veg', 'Indian Veg Combo Thali', 'A complete vegetarian Indian platter with paneer, mixed veg, dal, rice, roti, and dessert.', 369, 'https://images.pexels.com/photos/8818723/pexels-photo-8818723.jpeg?auto=compress&cs=tinysrgb&h=400&w=600', 'Indian vegetarian thali with paneer, vegetables, dal, rice, and roti on a platter', 'veg', '1 person', ARRAY['Paneer Kadhai', 'Mix Veg', 'Dal Tadka', 'Steamed Rice', '2 Pcs Tawa Roti', 'Salad', 'Pickle', 'Papad', '1 Pc Gulab Jamun']::text[], true, 1),
  ('thali-indian-egg', 'Indian Egg Combo Thali', 'A fulfilling egg thali with egg curry, mixed veg, dal, rice, roti, and a sweet treat.', 379, 'https://images.pexels.com/photos/8818723/pexels-photo-8818723.jpeg?auto=compress&cs=tinysrgb&h=400&w=600', 'Indian egg thali with egg curry, vegetables, dal, rice, and roti', 'egg', '1 person', ARRAY['Egg Curry 1 Pc', 'Mix Veg', 'Dal Tadka', 'Steamed Rice', '2 Pcs Tawa Roti', 'Salad', 'Pickle', 'Papad', '1 Pc Gulab Jamun']::text[], false, 2),
  ('thali-indian-chicken', 'Indian Chicken Combo Thali', 'A hearty chicken thali with chicken curry, mixed veg, dal, rice, paratha, and dessert.', 469, 'https://images.pexels.com/photos/5775684/pexels-photo-5775684.jpeg?auto=compress&cs=tinysrgb&h=400&w=600', 'Indian chicken thali with chicken curry, vegetables, dal, rice, and paratha', 'non-veg', '1 person', ARRAY['Chicken Curry 1 Pc', 'Mix Veg', 'Dal Tadka', 'Steamed Rice', '2 Laccha Paratha', 'Salad', 'Pickle', 'Papad', '1 Pc Gulab Jamun']::text[], true, 3),
  ('thali-indian-mutton', 'Indian Mutton Combo Thali', 'A royal mutton thali with mutton curry, mixed veg, dal, rice, paratha, and dessert.', 589, 'https://images.pexels.com/photos/5775684/pexels-photo-5775684.jpeg?auto=compress&cs=tinysrgb&h=400&w=600', 'Indian mutton thali with mutton curry, vegetables, dal, rice, and paratha', 'non-veg', '1 person', ARRAY['Mutton Curry 1 Pc', 'Mix Veg', 'Dal Tadka', 'Steamed Rice', 'Laccha Paratha', 'Salad', 'Pickle', 'Papad', '1 Pc Gulab Jamun']::text[], false, 4),
  ('thali-chinese-veg', 'Chinese Veg Combo Thali', 'A Chinese-style veg platter with Manchurian, noodles, fried rice, paratha, and dessert.', 389, 'https://images.pexels.com/photos/17050759/pexels-photo-17050759.jpeg?auto=compress&cs=tinysrgb&h=400&w=600', 'Chinese vegetarian combo with Manchurian, noodles, and fried rice', 'veg', '1 person', ARRAY['Veg Manchurian Dry', 'Veg Noodles', 'Veg Fried Rice', '2 Pcs Laccha Paratha', 'Kimchi Salad', '1 Pc Gulab Jamun']::text[], false, 5),
  ('thali-chinese-paneer', 'Chinese Paneer Combo Thali', 'A Chinese-style paneer platter with chilli paneer, noodles, fried rice, and dessert.', 429, 'https://images.pexels.com/photos/17050759/pexels-photo-17050759.jpeg?auto=compress&cs=tinysrgb&h=400&w=600', 'Chinese paneer combo with chilli paneer, noodles, and fried rice', 'veg', '1 person', ARRAY['Paneer Chilli Dry', 'Veg Noodles', 'Veg Fried Rice', '2 Pcs Laccha Paratha', 'Kimchi Salad', '1 Pc Gulab Jamun']::text[], false, 6),
  ('thali-chinese-chicken', 'Chinese Chicken Combo Thali', 'A Chinese-style chicken platter with chilli chicken, Hakka noodles, fried rice, and dessert.', 469, 'https://images.pexels.com/photos/17050759/pexels-photo-17050759.jpeg?auto=compress&cs=tinysrgb&h=400&w=600', 'Chinese chicken combo with chilli chicken, Hakka noodles, and fried rice', 'non-veg', '1 person', ARRAY['Chilli Chicken', 'Veg Hakka Noodles', 'Veg Fried Rice', '2 Pcs Laccha Paratha', 'Kimchi Salad', '1 Pc Gulab Jamun']::text[], true, 7)
ON CONFLICT (id) DO NOTHING;

