import type { ComboThali, MenuCategory } from '../types';

// ============================================================
// IMAGE URL POOL — one per category, items reuse the pool
// ============================================================

const P = 'https://images.pexels.com/photos/';
const S = '?auto=compress&cs=tinysrgb&h=400&w=400';
const PL = '?auto=compress&cs=tinysrgb&h=400&w=600';

const IMG = {
  // Beverages
  water: P + '327090/pexels-photo-327090.jpeg' + S,
  chai: P + '12865880/pexels-photo-12865880.jpeg' + S,
  masalaChai: P + '2697931/pexels-photo-2697931.jpeg' + S,
  lemonTea: P + '2633403/pexels-photo-2633403.jpeg' + S,
  coffee: P + '302899/pexels-photo-302899.jpeg' + S,
  limeWater: P + '96974/pexels-photo-96974.jpeg' + S,
  limeSoda: P + '16970621/pexels-photo-16970621.jpeg' + S,
  chaas: P + '8489749/pexels-photo-8489749.jpeg' + S,
  lassi: P + '18142603/pexels-photo-18142603.jpeg' + S,
  saltedLassi: P + '15522898/pexels-photo-15522898.jpeg' + S,
  softDrink: P + '2983100/pexels-photo-2983100.jpeg' + S,
  masalaSoda: P + '9996446/pexels-photo-9996446.jpeg' + S,
  masalaCoke: P + '15205136/pexels-photo-15205136.jpeg' + S,
  coldCoffee: P + '3908198/pexels-photo-3908198.jpeg' + S,
  coldCoffeeIceCream: P + '17558645/pexels-photo-17558645.jpeg' + S,
  // Soups
  manchowSoup: P + '5409027/pexels-photo-5409027.jpeg' + S,
  hotSourSoup: P + '25325508/pexels-photo-25325508.jpeg' + S,
  tomatoSoup: P + '4062272/pexels-photo-4062272.jpeg' + S,
  sweetCornSoup: P + '29631481/pexels-photo-29631481.jpeg' + S,
  noodleSoup: P + '8696758/pexels-photo-8696758.jpeg' + S,
  chickenManchowSoup: P + '16811678/pexels-photo-16811678.jpeg' + S,
  chickenHotSourSoup: P + '16845652/pexels-photo-16845652.jpeg' + S,
  chickenSweetCornSoup: P + '29538431/pexels-photo-29538431.jpeg' + S,
  chickenSoup: P + '10172749/pexels-photo-10172749.jpeg' + S,
  // Shakes
  shake: P + '38178695/pexels-photo-38178695.jpeg' + S,
  thickShake: P + '6174870/pexels-photo-6174870.jpeg' + S,
  kitKatShake: P + '30660270/pexels-photo-30660270.jpeg' + S,
  oreoShake: P + '11512980/pexels-photo-11512980.jpeg' + S,
  mangoShake: P + '6174874/pexels-photo-6174874.jpeg' + S,
  brownieShake: P + '13676051/pexels-photo-13676051.jpeg' + S,
  freakShake: P + '1146758/pexels-photo-1146758.jpeg' + S,
  // Quick Bites
  fries: P + '17354196/pexels-photo-17354196.jpeg' + S,
  pakoda: P + '33104648/pexels-photo-33104648.jpeg' + S,
  paneerPakoda: P + '8585763/pexels-photo-8585763.jpeg' + S,
  chickenPakoda: P + '33254639/pexels-photo-33254639.jpeg' + S,
  sandwich: P + '39195756/pexels-photo-39195756.jpeg' + S,
  mayoSandwich: P + '20422176/pexels-photo-20422176.jpeg' + S,
  springRoll: P + '29037269/pexels-photo-29037269.jpeg' + S,
  paneerSpringRoll: P + '4001867/pexels-photo-4001867.jpeg' + S,
  chickenSpringRoll: P + '8178762/pexels-photo-8178762.jpeg' + S,
  kathiRoll: P + '5713744/pexels-photo-5713744.jpeg' + S,
  eggKathiRoll: P + '2955819/pexels-photo-2955819.jpeg' + S,
  chickenKathiRoll: P + '12737661/pexels-photo-12737661.jpeg' + S,
  pavBhaji: P + '166654/pexels-photo-166654.jpeg' + S,
  // Indo-Chinese
  manchurian: P + '29631489/pexels-photo-29631489.jpeg' + S,
  honeyChilliPotato: P + '11485199/pexels-photo-11485199.jpeg' + S,
  chilliPaneer: P + '29631468/pexels-photo-29631468.jpeg' + S,
  paneer65: P + '8585763/pexels-photo-8585763.jpeg' + S,
  paneerManchurianDry: P + '31783383/pexels-photo-31783383.jpeg' + S,
  paneerSaltPepper: P + '29631461/pexels-photo-29631461.jpeg' + S,
  hotGarlicPaneer: P + '8414639/pexels-photo-8414639.jpeg' + S,
  mushroom: P + '30546532/pexels-photo-30546532.jpeg' + S,
  friedMushroom: P + '13065199/pexels-photo-13065199.jpeg' + S,
  babyCorn: P + '34203235/pexels-photo-34203235.jpeg' + S,
  babyCornSaltPepper: P + '2734288/pexels-photo-2734288.jpeg' + S,
  pasta: P + '1438672/pexels-photo-1438672.jpeg' + S,
  creamyPasta: P + '34363091/pexels-photo-34363091.jpeg' + S,
  chilliPasta: P + '5419339/pexels-photo-5419339.jpeg' + S,
  maggi: P + '4635600/pexels-photo-4635600.jpeg' + S,
  chilliChicken: P + '18698224/pexels-photo-18698224.jpeg' + S,
  drumsHeaven: P + '29631422/pexels-photo-29631422.jpeg' + S,
  chicken65: P + '5946434/pexels-photo-5946434.jpeg' + S,
  chickenManchurian: P + '29631426/pexels-photo-29631426.jpeg' + S,
  hotGarlicChicken: P + '28674534/pexels-photo-28674534.jpeg' + S,
  chickenSaltPepper: P + '32722824/pexels-photo-32722824.jpeg' + S,
  friedChicken: P + '5652266/pexels-photo-5652266.jpeg' + S,
  // Tandoor Veg
  paneerTikka: P + '3928854/pexels-photo-3928854.png' + S,
  achariPaneerTikka: P + '20395267/pexels-photo-20395267.jpeg' + S,
  paneerMalai: P + '29173105/pexels-photo-29173105.jpeg' + S,
  kalimirchPaneerTikka: P + '33430558/pexels-photo-33430558.jpeg' + S,
  paneerSeekh: P + '8414670/pexels-photo-8414670.jpeg' + S,
  paneerMalaiSeekh: P + '9609850/pexels-photo-9609850.jpeg' + S,
  tandooriMushroom: P + '6646154/pexels-photo-6646154.jpeg' + S,
  mushroomTikka: P + '29173103/pexels-photo-29173103.jpeg' + S,
  mushroomMalaiTikka: P + '34429561/pexels-photo-34429561.jpeg' + S,
  haraBhara: P + '6853406/pexels-photo-6853406.jpeg' + S,
  dahiKeKabab: P + '26245461/pexels-photo-26245461.jpeg' + S,
  vegSeekh: P + '37080242/pexels-photo-37080242.jpeg' + S,
  vegMalaiSeekh: P + '38579058/pexels-photo-38579058.jpeg' + S,
  alooGobhi: P + '9213977/pexels-photo-9213977.jpeg' + S,
  // Tandoor Non-Veg
  tandooriChicken: P + '36895285/pexels-photo-36895285.jpeg' + S,
  afghaniChicken: P + '29685054/pexels-photo-29685054.jpeg' + S,
  chickenTikka: P + '16423838/pexels-photo-16423838.jpeg' + S,
  achariChickenTikka: P + '29173114/pexels-photo-29173114.jpeg' + S,
  greenChickenTikka: P + '27848435/pexels-photo-27848435.jpeg' + S,
  chickenAngaraTikka: P + '30749024/pexels-photo-30749024.jpeg' + S,
  chickenMalaiTikka: P + '18877581/pexels-photo-18877581.jpeg' + S,
  chickenKalimirchTikka: P + '20371512/pexels-photo-20371512.jpeg' + S,
  chickenReshmiTikka: P + '30021858/pexels-photo-30021858.jpeg' + S,
  kalimirchAfghaniChicken: P + '12737659/pexels-photo-12737659.jpeg' + S,
  chickenSeekh: P + '9646858/pexels-photo-9646858.jpeg' + S,
  afghaniSeekh: P + '38579058/pexels-photo-38579058.jpeg' + S,
  muttonSeekh: P + '18698226/pexels-photo-18698226.jpeg' + S,
  // Veg Main Course
  paneerButterMasala: P + '29685056/pexels-photo-29685056.jpeg' + S,
  kadhaiPaneer: P + '29631461/pexels-photo-29631461.jpeg' + S,
  sahiPaneer: P + '11115801/pexels-photo-11115801.jpeg' + S,
  paneerLababdar: P + '12737799/pexels-photo-12737799.jpeg' + S,
  paneerTikkaMasala: P + '30858402/pexels-photo-30858402.jpeg' + S,
  paneerPunjabi: P + '5127316/pexels-photo-5127316.jpeg' + S,
  paneerKolhapuri: P + '13823417/pexels-photo-13823417.jpeg' + S,
  paneerHandi: P + '36460902/pexels-photo-36460902.jpeg' + S,
  paneerDoPyaza: P + '28674562/pexels-photo-28674562.jpeg' + S,
  paneerMutterMasala: P + '9609842/pexels-photo-9609842.jpeg' + S,
  paneerKofta: P + '28674560/pexels-photo-28674560.jpeg' + S,
  vegMalaiKofta: P + '36343375/pexels-photo-36343375.jpeg' + S,
  dalMakhani: P + '37182513/pexels-photo-37182513.jpeg' + S,
  dalTadka: P + '37182514/pexels-photo-37182514.jpeg' + S,
  mushroomMasala: P + '35041649/pexels-photo-35041649.jpeg' + S,
  mushroomTikkaMasala: P + '35041650/pexels-photo-35041650.jpeg' + S,
  mushroomMutterMasala: P + '11325184/pexels-photo-11325184.jpeg' + S,
  mushroomDoPyaza: P + '20446423/pexels-photo-20446423.jpeg' + S,
  babyCornMushroomMasala: P + '35041660/pexels-photo-35041660.jpeg' + S,
  alooGobhiMasala: P + '2116093/pexels-photo-2116093.jpeg' + S,
  mixVeg: P + '35267281/pexels-photo-35267281.jpeg' + S,
  bhindi: P + '33643313/pexels-photo-33643313.jpeg' + S,
  alooDum: P + '19781596/pexels-photo-19781596.jpeg' + S,
  chole: P + '17223838/pexels-photo-17223838.jpeg' + S,
  // Non-Veg Main Course
  butterChicken: P + '29685054/pexels-photo-29685054.jpeg' + S,
  chickenAhunna: P + '29684988/pexels-photo-29684988.jpeg' + S,
  chickenCurry: P + '29684987/pexels-photo-29684987.jpeg' + S,
  chickenDehati: P + '37180955/pexels-photo-37180955.jpeg' + S,
  chickenTikkaMasalaCurry: P + '38400477/pexels-photo-38400477.jpeg' + S,
  chickenHandiCurry: P + '34159108/pexels-photo-34159108.jpeg' + S,
  chickenKolhapuriCurry: P + '29684985/pexels-photo-29684985.jpeg' + S,
  chickenKassa: P + '29685081/pexels-photo-29685081.jpeg' + S,
  chickenDoPyazaCurry: P + '6113813/pexels-photo-6113813.jpeg' + S,
  chickenIstu: P + '38003491/pexels-photo-38003491.jpeg' + S,
  chickenCurryBowl: P + '32986463/pexels-photo-32986463.jpeg' + S,
  muttonCurry: P + '28674690/pexels-photo-28674690.jpeg' + S,
  eggCurry: P + '35071817/pexels-photo-35071817.jpeg' + S,
  eggMasala: P + '34217294/pexels-photo-34217294.jpeg' + S,
  chickenMasalaCurry: P + '31692606/pexels-photo-31692606.jpeg' + S,
  muttonDoPyazaCurry: P + '28674568/pexels-photo-28674568.jpeg' + S,
  muttonHandiCurry: P + '9609849/pexels-photo-9609849.jpeg' + S,
  // Breads
  naan: P + '30203311/pexels-photo-30203311.jpeg' + S,
  butterNaan: P + '38163958/pexels-photo-38163958.jpeg' + S,
  garlicNaan: P + '10337726/pexels-photo-10337726.jpeg' + S,
  roti: P + '28674556/pexels-photo-28674556.jpeg' + S,
  tawaRoti: P + '5589943/pexels-photo-5589943.jpeg' + S,
  tandooriRoti: P + '36840077/pexels-photo-36840077.jpeg' + S,
  butterTandooriRoti: P + '12737800/pexels-photo-12737800.jpeg' + S,
  paratha: P + '37555450/pexels-photo-37555450.jpeg' + S,
  lacchaParatha: P + '38834853/pexels-photo-38834853.jpeg' + S,
  kulcha: P + '6183640/pexels-photo-6183640.jpeg' + S,
  onionKulcha: P + '12737664/pexels-photo-12737664.jpeg' + S,
  paneerKulcha: P + '12737919/pexels-photo-12737919.jpeg' + S,
  keemaNaan: P + '32986478/pexels-photo-32986478.jpeg' + S,
  // Salad & Raita
  salad: P + '842545/pexels-photo-842545.jpeg' + S,
  papad: P + '4887993/pexels-photo-4887993.jpeg' + S,
  friedPapad: P + '34739831/pexels-photo-34739831.jpeg' + S,
  masalaPapad: P + '34270742/pexels-photo-34270742.jpeg' + S,
  masalaPeanut: P + '14823164/pexels-photo-14823164.jpeg' + S,
  raita: P + '29699511/pexels-photo-29699511.jpeg' + S,
  mixVegRaita: P + '35552954/pexels-photo-35552954.jpeg' + S,
  kheeraRaita: P + '35552952/pexels-photo-35552952.jpeg' + S,
  poodinaRaita: P + '32235866/pexels-photo-32235866.jpeg' + S,
  // Desserts
  gulabJamun: P + '11887844/pexels-photo-11887844.jpeg' + S,
  rasgulla: P + '37133961/pexels-photo-37133961.jpeg' + S,
  rasmalai: P + '14610769/pexels-photo-14610769.jpeg' + S,
  iceCream: P + '36576778/pexels-photo-36576778.jpeg' + S,
  // Rice & Biryani
  rice: P + '35552983/pexels-photo-35552983.jpeg' + S,
  basmatiRice: P + '39493671/pexels-photo-39493671.jpeg' + S,
  jeeraRice: P + '28674713/pexels-photo-28674713.jpeg' + S,
  biryani: P + '17696655/pexels-photo-17696655.jpeg' + S,
  muttonBiryani: P + '32986475/pexels-photo-32986475.jpeg' + S,
  friedRice: P + '9045147/pexels-photo-9045147.jpeg' + S,
  eggFriedRice: P + '28503583/pexels-photo-28503583.jpeg' + S,
  paneerFriedRice: P + '29631461/pexels-photo-29631461.jpeg' + S,
  chickenFriedRice: P + '34668500/pexels-photo-34668500.jpeg' + S,
  schezwanChickenFriedRice: P + '6705486/pexels-photo-6705486.jpeg' + S,
  eggChickenFriedRice: P + '37171028/pexels-photo-37171028.jpeg' + S,
  mushroomFriedRice: P + '32489477/pexels-photo-32489477.jpeg' + S,
  schezwanFriedRice: P + '31783383/pexels-photo-31783383.jpeg' + S,
  specialFriedRice: P + '35071826/pexels-photo-35071826.jpeg' + S,
  vegBiryani: P + '37303308/pexels-photo-37303308.jpeg' + S,
  eggBiryani: P + '31537385/pexels-photo-31537385.jpeg' + S,
  paneerBiryani: P + '9609859/pexels-photo-9609859.jpeg' + S,
  chickenBiryani: P + '7340936/pexels-photo-7340936.jpeg' + S,
  // Noodles
  noodles: P + '12737657/pexels-photo-12737657.jpeg' + S,
  chowmein: P + '20791757/pexels-photo-20791757.jpeg' + S,
  schezwanNoodles: P + '28445827/pexels-photo-28445827.jpeg' + S,
  garlicNoodles: P + '10913411/pexels-photo-10913411.jpeg' + S,
  paneerNoodles: P + '37165674/pexels-photo-37165674.jpeg' + S,
  mushroomNoodles: P + '34899288/pexels-photo-34899288.jpeg' + S,
  specialNoodles: P + '28674525/pexels-photo-28674525.jpeg' + S,
  schezwanChickenNoodles: P + '34170982/pexels-photo-34170982.jpeg' + S,
  garlicChickenNoodles: P + '9395910/pexels-photo-9395910.jpeg' + S,
  eggChickenNoodles: P + '37331002/pexels-photo-37331002.jpeg' + S,
  signatureChickenNoodles: P + '28460865/pexels-photo-28460865.jpeg' + S,
  chickenNoodles: P + '18698263/pexels-photo-18698263.jpeg' + S,
  // Thali
  vegThali: P + '8818723/pexels-photo-8818723.jpeg' + PL,
  eggThali: P + '32797056/pexels-photo-32797056.jpeg' + PL,
  nonVegThali: P + '5775684/pexels-photo-5775684.jpeg' + PL,
  muttonThali: P + '36885716/pexels-photo-36885716.jpeg' + PL,
  chineseThali: P + '17050759/pexels-photo-17050759.jpeg' + PL,
  chinesePaneerThali: P + '28445828/pexels-photo-28445828.jpeg' + PL,
  chineseChickenThali: P + '28445829/pexels-photo-28445829.jpeg' + PL,
};

// ============================================================
// COMBO THALIS (Section 14)
// ============================================================

export const comboThalis: ComboThali[] = [
  {
    id: 'thali-indian-veg',
    name: 'Indian Veg Combo Thali',
    description: 'A complete vegetarian Indian platter with paneer, mixed veg, dal, rice, roti, and dessert.',
    price: 369,
    image: IMG.vegThali,
    imageAlt: 'Indian vegetarian thali with paneer, vegetables, dal, rice, and roti on a platter',
    diet: 'veg',
    serves: '1 person',
    items: [
      'Paneer Kadhai',
      'Mix Veg',
      'Dal Tadka',
      'Steamed Rice',
      '2 Pcs Tawa Roti',
      'Salad',
      'Pickle',
      'Papad',
      '1 Pc Gulab Jamun',
    ],
    popular: true,
  },
  {
    id: 'thali-indian-egg',
    name: 'Indian Egg Combo Thali',
    description: 'A fulfilling egg thali with egg curry, mixed veg, dal, rice, roti, and a sweet treat.',
    price: 379,
    image: IMG.eggThali,
    imageAlt: 'Indian egg thali with egg curry, vegetables, dal, rice, and roti',
    diet: 'egg',
    serves: '1 person',
    items: [
      'Egg Curry 1 Pc',
      'Mix Veg',
      'Dal Tadka',
      'Steamed Rice',
      '2 Pcs Tawa Roti',
      'Salad',
      'Pickle',
      'Papad',
      '1 Pc Gulab Jamun',
    ],
  },
  {
    id: 'thali-indian-chicken',
    name: 'Indian Chicken Combo Thali',
    description: 'A hearty chicken thali with chicken curry, mixed veg, dal, rice, paratha, and dessert.',
    price: 469,
    image: IMG.nonVegThali,
    imageAlt: 'Indian chicken thali with chicken curry, vegetables, dal, rice, and paratha',
    diet: 'non-veg',
    serves: '1 person',
    items: [
      'Chicken Curry 1 Pc',
      'Mix Veg',
      'Dal Tadka',
      'Steamed Rice',
      '2 Laccha Paratha',
      'Salad',
      'Pickle',
      'Papad',
      '1 Pc Gulab Jamun',
    ],
    popular: true,
  },
  {
    id: 'thali-indian-mutton',
    name: 'Indian Mutton Combo Thali',
    description: 'A royal mutton thali with mutton curry, mixed veg, dal, rice, paratha, and dessert.',
    price: 589,
    image: IMG.muttonThali,
    imageAlt: 'Indian mutton thali with mutton curry, vegetables, dal, rice, and paratha',
    diet: 'non-veg',
    serves: '1 person',
    items: [
      'Mutton Curry 1 Pc',
      'Mix Veg',
      'Dal Tadka',
      'Steamed Rice',
      'Laccha Paratha',
      'Salad',
      'Pickle',
      'Papad',
      '1 Pc Gulab Jamun',
    ],
  },
  {
    id: 'thali-chinese-veg',
    name: 'Chinese Veg Combo Thali',
    description: 'A Chinese-style veg platter with Manchurian, noodles, fried rice, paratha, and dessert.',
    price: 389,
    image: IMG.chineseThali,
    imageAlt: 'Chinese vegetarian combo with Manchurian, noodles, and fried rice',
    diet: 'veg',
    serves: '1 person',
    items: [
      'Veg Manchurian Dry',
      'Veg Noodles',
      'Veg Fried Rice',
      '2 Pcs Laccha Paratha',
      'Kimchi Salad',
      '1 Pc Gulab Jamun',
    ],
  },
  {
    id: 'thali-chinese-paneer',
    name: 'Chinese Paneer Combo Thali',
    description: 'A Chinese-style paneer platter with chilli paneer, noodles, fried rice, and dessert.',
    price: 429,
    image: IMG.chinesePaneerThali,
    imageAlt: 'Chinese paneer combo with chilli paneer, noodles, and fried rice',
    diet: 'veg',
    serves: '1 person',
    items: [
      'Paneer Chilli Dry',
      'Veg Noodles',
      'Veg Fried Rice',
      '2 Pcs Laccha Paratha',
      'Kimchi Salad',
      '1 Pc Gulab Jamun',
    ],
  },
  {
    id: 'thali-chinese-chicken',
    name: 'Chinese Chicken Combo Thali',
    description: 'A Chinese-style chicken platter with chilli chicken, Hakka noodles, fried rice, and dessert.',
    price: 469,
    image: IMG.chineseChickenThali,
    imageAlt: 'Chinese chicken combo with chilli chicken, Hakka noodles, and fried rice',
    diet: 'non-veg',
    serves: '1 person',
    items: [
      'Chilli Chicken',
      'Veg Hakka Noodles',
      'Veg Fried Rice',
      '2 Pcs Laccha Paratha',
      'Kimchi Salad',
      '1 Pc Gulab Jamun',
    ],
    popular: true,
  },
];

// ============================================================
// MENU CATEGORIES (Sections 1–13)
// ============================================================

export const menuCategories: MenuCategory[] = [
  // ─── 1. BEVERAGES – SIPS & BREWS ───
  {
    id: 'beverages',
    label: 'Beverages — Sips & Brews',
    shortLabel: 'Beverages',
    items: [
      { id: 'bv-001', name: 'Packaged Drinking Water', description: '1000ML — MRP', price: 20, image: IMG.water, imageAlt: 'Packaged drinking water bottle', diet: 'veg', serves: '1000ML' },
      { id: 'bv-002', name: 'Regular Hot Tea', description: 'Classic Indian tea brewed with milk and sugar.', price: 52, image: IMG.chai, imageAlt: 'Hot tea in a glass', diet: 'veg', serves: '200ML' },
      { id: 'bv-003', name: "Popular's Special Masala Chai", description: 'Our signature masala chai with aromatic spices.', price: 59, image: IMG.masalaChai, imageAlt: 'Masala chai with spices in a glass', diet: 'veg', popular: true, serves: '200ML' },
      { id: 'bv-004', name: 'Zesty Lemon Tea', description: 'Refreshing hot tea infused with fresh lemon.', price: 49, image: IMG.lemonTea, imageAlt: 'Lemon tea in a cup', diet: 'veg', serves: '200ML' },
      { id: 'bv-005', name: 'Classic Hot Coffee', description: 'Freshly brewed hot coffee, rich and aromatic.', price: 129, image: IMG.coffee, imageAlt: 'Hot coffee in a mug', diet: 'veg', serves: '200ML' },
      { id: 'bv-006', name: 'Fresh Lime Water', description: 'Cooling lime water with a hint of mint.', price: 90, image: IMG.limeWater, imageAlt: 'Fresh lime water with mint', diet: 'veg', serves: '300ML' },
      { id: 'bv-007', name: 'Refreshing Fresh Lime Soda', description: 'Sparkling soda with fresh lime juice.', price: 119, image: IMG.limeSoda, imageAlt: 'Fresh lime soda in a glass', diet: 'veg', serves: '300ML' },
      { id: 'bv-008', name: 'Desi Masala Chaas', description: 'Spiced buttermilk with cumin and curry leaves.', price: 109, image: IMG.chaas, imageAlt: 'Masala chaas in a clay cup', diet: 'veg', serves: '200ML' },
      { id: 'bv-009', name: 'Punjabi Sweet Lassi', description: 'Thick and creamy sweet yogurt drink.', price: 129, image: IMG.lassi, imageAlt: 'Sweet lassi in a tall glass', diet: 'veg', popular: true, serves: '200ML' },
      { id: 'bv-010', name: 'Classic Salted Lassi', description: 'Refreshing salted yogurt drink with cumin.', price: 129, image: IMG.saltedLassi, imageAlt: 'Salted lassi in a glass', diet: 'veg', serves: '300ML' },
      { id: 'bv-011', name: 'Assorted Soft Drinks', description: 'Choice of Pepsi, 7Up, Mirinda, and more.', price: 79, image: IMG.softDrink, imageAlt: 'Assorted soft drink bottles', diet: 'veg', serves: '200ML' },
      { id: 'bv-012', name: 'Fizzy Masala Soda', description: 'Spiced carbonated soda with a tangy kick.', price: 89, image: IMG.masalaSoda, imageAlt: 'Masala soda in a bottle', diet: 'veg', serves: '300ML' },
      { id: 'bv-013', name: 'Chatpata Masala Coke', description: 'Coke spiced with masala for a desi twist.', price: 109, image: IMG.masalaCoke, imageAlt: 'Masala coke in a glass', diet: 'veg', serves: '300ML' },
      { id: 'bv-014', name: 'Chilled Cold Coffee', description: 'Iced cold coffee blended to perfection.', price: 189, image: IMG.coldCoffee, imageAlt: 'Cold coffee in a tall glass', diet: 'veg', popular: true, serves: '300ML' },
      { id: 'bv-015', name: 'Indulgent Cold Coffee with Ice Cream', description: 'Cold coffee topped with a scoop of ice cream.', price: 209, image: IMG.coldCoffeeIceCream, imageAlt: 'Cold coffee with ice cream on top', diet: 'veg', chefSpecial: true, serves: '300ML' },
    ],
  },

  // ─── 2. SOUL-WARMING SOUP + SHAKES ───
  {
    id: 'soups-shakes',
    label: 'Soul-Warming Soup + Shakes',
    shortLabel: 'Soup + Shakes',
    items: [
      // Soups
      { id: 'sp-001', name: 'Classic Veg Manchow Soup', description: 'Spicy vegetable soup with fried noodles topping.', price: 209, image: IMG.manchowSoup, imageAlt: 'Veg Manchow soup with crispy noodles', diet: 'veg', spice: 'medium', serves: '1 bowl' },
      { id: 'sp-002', name: 'Veg Hot & Sour Soup', description: 'Tangy and spicy vegetable soup with a bold kick.', price: 209, image: IMG.hotSourSoup, imageAlt: 'Hot and sour vegetable soup', diet: 'veg', spice: 'hot', serves: '1 bowl' },
      { id: 'sp-003', name: 'Rich Cream of Tomato Soup', description: 'Velvety tomato soup with fresh cream.', price: 199, image: IMG.tomatoSoup, imageAlt: 'Cream of tomato soup', diet: 'veg', serves: '1 bowl' },
      { id: 'sp-004', name: 'Comforting Veg Sweet Corn Soup', description: 'Creamy sweet corn soup with vegetables.', price: 209, image: IMG.sweetCornSoup, imageAlt: 'Sweet corn vegetable soup', diet: 'veg', serves: '1 bowl' },
      { id: 'sp-005', name: 'Veg Noodle Soup', description: 'Hearty noodle soup with fresh vegetables.', price: 219, image: IMG.noodleSoup, imageAlt: 'Vegetable noodle soup', diet: 'veg', serves: '1 bowl' },
      { id: 'sp-006', name: "Chef's Special Chicken Manchow Soup", description: 'Spicy chicken soup topped with crispy noodles.', price: 219, image: IMG.chickenManchowSoup, imageAlt: 'Chicken Manchow soup with noodles', diet: 'non-veg', spice: 'medium', chefSpecial: true, serves: '1 bowl' },
      { id: 'sp-007', name: 'Chicken Hot & Sour Soup', description: 'Tangy and spicy chicken soup with vegetables.', price: 219, image: IMG.chickenHotSourSoup, imageAlt: 'Chicken hot and sour soup', diet: 'non-veg', spice: 'hot', serves: '1 bowl' },
      { id: 'sp-008', name: 'Comforting Chicken Sweet Corn Soup', description: 'Creamy sweet corn soup with shredded chicken.', price: 209, image: IMG.chickenSweetCornSoup, imageAlt: 'Chicken sweet corn soup', diet: 'non-veg', serves: '1 bowl' },
      { id: 'sp-009', name: 'Hearty Chicken Noodle Soup', description: 'Wholesome chicken noodle soup with vegetables.', price: 249, image: IMG.chickenSoup, imageAlt: 'Chicken noodle soup', diet: 'non-veg', serves: '1 bowl' },
      // Shakes
      { id: 'sp-010', name: 'Regular Milk Shake', description: 'Classic milk shake in your favourite flavour.', price: 159, image: IMG.shake, imageAlt: 'Regular milk shake in a glass', diet: 'veg', serves: '1 glass' },
      { id: 'sp-011', name: 'Classic Thick Milk Shake', description: 'Rich thick shake — Vanilla / Strawberry / Butterscotch / Chocolate.', price: 199, image: IMG.thickShake, imageAlt: 'Thick milk shake with whipped cream', diet: 'veg', serves: '1 glass' },
      { id: 'sp-012', name: 'Kit Kat Shake', description: 'Creamy shake loaded with crushed Kit Kat.', price: 209, image: IMG.kitKatShake, imageAlt: 'Kit Kat milk shake', diet: 'veg', popular: true, serves: '1 glass' },
      { id: 'sp-013', name: 'Oreo Cookie Shake', description: 'Thick shake blended with Oreo cookies.', price: 219, image: IMG.oreoShake, imageAlt: 'Oreo cookie milk shake', diet: 'veg', serves: '1 glass' },
      { id: 'sp-014', name: 'Mango Bloom', description: 'Refreshing mango shake with seasonal mango pulp.', price: 219, image: IMG.mangoShake, imageAlt: 'Mango milk shake', diet: 'veg', serves: '1 glass' },
      { id: 'sp-015', name: 'Choco Brownie Shake', description: 'Indulgent shake with chocolate brownie chunks.', price: 249, image: IMG.brownieShake, imageAlt: 'Chocolate brownie shake', diet: 'veg', chefSpecial: true, serves: '1 glass' },
      { id: 'sp-016', name: 'Popular Freak Shake', description: 'Over-the-top freak shake with brownie, ice cream, and toppings.', price: 309, image: IMG.freakShake, imageAlt: 'Freak shake with brownie and ice cream toppings', diet: 'veg', popular: true, chefSpecial: true, serves: '1 glass' },
    ],
  },

  // ─── 3. QUICK BITES – ROLLS | SANDWICHES | SNACKS ───
  {
    id: 'quick-bites',
    label: 'Quick Bites — Rolls | Sandwiches | Snacks',
    shortLabel: 'Quick Bites',
    items: [
      { id: 'qb-001', name: 'Classic Salted French Fries', description: 'Golden crispy fries sprinkled with salt.', price: 199, image: IMG.fries, imageAlt: 'Salted french fries with ketchup', diet: 'veg', popular: true, serves: '1 plate' },
      { id: 'qb-002', name: 'Crunchy Onion Pakoda', description: 'Crispy onion fritters deep-fried to golden perfection.', price: 169, image: IMG.pakoda, imageAlt: 'Onion pakoda fritters', diet: 'veg', serves: '1 plate' },
      { id: 'qb-003', name: 'Golden Paneer Pakoda', description: 'Cottage cheese fritters with a crispy coating.', price: 239, image: IMG.paneerPakoda, imageAlt: 'Paneer pakoda fritters', diet: 'veg', serves: '1 plate' },
      { id: 'qb-004', name: 'Crispy Chicken Pakoda', description: 'Spiced chicken fritters, crunchy outside and juicy inside.', price: 329, image: IMG.chickenPakoda, imageAlt: 'Chicken pakoda fritters', diet: 'non-veg', spice: 'medium', serves: '1 plate' },
      { id: 'qb-005', name: 'Creamy Veg Mayo Sandwich', description: 'Vegetable sandwich with creamy mayo dressing.', price: 199, image: IMG.mayoSandwich, imageAlt: 'Veg mayo sandwich with fries', diet: 'veg', serves: '1 plate' },
      { id: 'qb-006', name: 'Bombay Style Veg Sandwich', description: 'Classic Mumbai street-style vegetable sandwich.', price: 199, image: IMG.sandwich, imageAlt: 'Bombay style veg sandwich', diet: 'veg', serves: '1 plate' },
      { id: 'qb-007', name: 'Crunchy Veg Spring Roll', description: 'Crispy spring rolls stuffed with seasoned vegetables.', price: 219, image: IMG.springRoll, imageAlt: 'Crispy vegetable spring rolls', diet: 'veg', serves: '1 plate' },
      { id: 'qb-008', name: 'Cheesy Paneer Spring Roll', description: 'Spring rolls filled with paneer and melted cheese.', price: 229, image: IMG.paneerSpringRoll, imageAlt: 'Paneer cheese spring rolls', diet: 'veg', serves: '1 plate' },
      { id: 'qb-009', name: 'Crispy Chicken Spring Roll', description: 'Golden spring rolls stuffed with spiced chicken.', price: 259, image: IMG.chickenSpringRoll, imageAlt: 'Chicken spring rolls', diet: 'non-veg', spice: 'medium', serves: '1 plate' },
      { id: 'qb-010', name: 'Crispy Veg Kathi Roll', description: 'Vegetable-filled Kathi roll wrapped in flaky paratha.', price: 199, image: IMG.kathiRoll, imageAlt: 'Veg kathi roll wrap', diet: 'veg', serves: '1 roll' },
      { id: 'qb-011', name: 'Street Style Egg Kathi Roll', description: 'Egg-filled Kathi roll with onions and spices.', price: 209, image: IMG.eggKathiRoll, imageAlt: 'Egg kathi roll wrap', diet: 'egg', serves: '1 roll' },
      { id: 'qb-012', name: "Popular Spl. Chicken Kathi Roll", description: 'Our special chicken Kathi roll with signature masala.', price: 219, image: IMG.chickenKathiRoll, imageAlt: 'Chicken kathi roll wrap', diet: 'non-veg', spice: 'medium', popular: true, serves: '1 roll' },
      { id: 'qb-013', name: 'Special Pav Bhaji', description: 'Buttery mashed vegetable curry served with toasted pav.', price: 209, image: IMG.pavBhaji, imageAlt: 'Pav bhaji with buttered buns', diet: 'veg', popular: true, serves: '1 plate' },
    ],
  },

  // ─── 4. APPETIZERS – INDO-CHINESE STARTERS ───
  {
    id: 'indo-chinese',
    label: 'Appetizers — Indo-Chinese Starters',
    shortLabel: 'Indo-Chinese Starters',
    items: [
      // Veg Chinese
      { id: 'ic-001', name: 'Classic Veg Manchurian (Dry/Gravy)', description: 'Veg Manchurian balls in tangy sauce — dry or gravy.', price: 259, image: IMG.manchurian, imageAlt: 'Veg Manchurian balls with sauce', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'ic-002', name: 'Sweet & Spicy Honey Chilli Potato', description: 'Crispy potato tossed in honey chilli sauce.', price: 220, image: IMG.honeyChilliPotato, imageAlt: 'Honey chilli potato with sauce', diet: 'veg', spice: 'medium', popular: true, serves: '1 plate' },
      { id: 'ic-003', name: 'Spicy Chilli Paneer (Dry/Gravy)', description: 'Paneer cubes tossed in spicy chilli sauce.', price: 350, image: IMG.chilliPaneer, imageAlt: 'Chilli paneer in sauce', diet: 'veg', spice: 'hot', serves: '1 plate' },
      { id: 'ic-004', name: 'Paneer 65', description: 'Crispy spiced paneer bites with curry leaves.', price: 324, image: IMG.paneer65, imageAlt: 'Paneer 65 crispy bites', diet: 'veg', spice: 'hot', serves: '1 plate' },
      { id: 'ic-005', name: 'Zesty Paneer Manchurian Dry', description: 'Paneer Manchurian tossed in a zesty dry sauce.', price: 324, image: IMG.paneerManchurianDry, imageAlt: 'Paneer Manchurian dry', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'ic-006', name: 'Crispy Paneer Salt & Pepper', description: 'Crispy paneer tossed with salt, pepper, and herbs.', price: 350, image: IMG.paneerSaltPepper, imageAlt: 'Paneer salt and pepper', diet: 'veg', serves: '1 plate' },
      { id: 'ic-007', name: 'Hot Garlic Tossed Paneer', description: 'Paneer tossed in a fiery hot garlic sauce.', price: 363, image: IMG.hotGarlicPaneer, imageAlt: 'Hot garlic paneer', diet: 'veg', spice: 'hot', serves: '1 plate' },
      { id: 'ic-008', name: 'Spicy Chilli Mushroom', description: 'Mushrooms tossed in spicy chilli sauce.', price: 324, image: IMG.mushroom, imageAlt: 'Chilli mushroom', diet: 'veg', spice: 'hot', serves: '1 plate' },
      { id: 'ic-009', name: 'Crispy Fried Mushroom', description: 'Golden crispy fried mushrooms with herbs.', price: 324, image: IMG.friedMushroom, imageAlt: 'Crispy fried mushrooms', diet: 'veg', serves: '1 plate' },
      { id: 'ic-010', name: 'Chilli Tossed Baby Corn', description: 'Baby corn tossed in spicy chilli sauce.', price: 311, image: IMG.babyCorn, imageAlt: 'Chilli baby corn', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'ic-011', name: 'Baby Corn Salt & Pepper', description: 'Crispy baby corn with salt, pepper, and herbs.', price: 311, image: IMG.babyCornSaltPepper, imageAlt: 'Baby corn salt and pepper', diet: 'veg', serves: '1 plate' },
      { id: 'ic-012', name: 'Veggies Macaroni Pasta', description: 'Macaroni tossed with vegetables and spices.', price: 233, image: IMG.pasta, imageAlt: 'Vegetable macaroni pasta', diet: 'veg', serves: '1 plate' },
      { id: 'ic-013', name: 'Creamy Macaroni Pasta', description: 'Macaroni in a rich and creamy white sauce.', price: 311, image: IMG.creamyPasta, imageAlt: 'Creamy macaroni pasta', diet: 'veg', serves: '1 plate' },
      { id: 'ic-014', name: 'Vegetable Masala Maggi', description: 'Instant noodles tossed with vegetables and masala.', price: 207, image: IMG.maggi, imageAlt: 'Vegetable masala Maggi noodles', diet: 'veg', popular: true, serves: '1 plate' },
      { id: 'ic-015', name: 'Classic Chilli Pasta', description: 'Pasta tossed in a spicy chilli sauce with veggies.', price: 259, image: IMG.chilliPasta, imageAlt: 'Chilli pasta with vegetables', diet: 'veg', spice: 'medium', serves: '1 plate' },
      // Non-Veg Chinese
      { id: 'ic-016', name: "Popular's Signature Chilli Chicken", description: 'Our signature chilli chicken with a fiery sauce.', price: 363, image: IMG.chilliChicken, imageAlt: 'Chilli chicken with peppers', diet: 'non-veg', spice: 'hot', popular: true, chefSpecial: true, serves: '1 plate' },
      { id: 'ic-017', name: "Chef's Special Drums of Heaven", description: 'Crispy chicken drumettes tossed in a sweet-spicy glaze.', price: 415, image: IMG.drumsHeaven, imageAlt: 'Drums of heaven chicken', diet: 'non-veg', spice: 'medium', chefSpecial: true, serves: '1 plate' },
      { id: 'ic-018', name: 'Chicken 65', description: 'Spicy deep-fried chicken with curry leaves.', price: 363, image: IMG.chicken65, imageAlt: 'Chicken 65 fried bites', diet: 'non-veg', spice: 'hot', serves: '1 plate' },
      { id: 'ic-019', name: 'Classic Chicken Manchurian', description: 'Chicken Manchurian in a tangy Indo-Chinese gravy.', price: 350, image: IMG.chickenManchurian, imageAlt: 'Chicken Manchurian with sauce', diet: 'non-veg', spice: 'medium', serves: '1 plate' },
      { id: 'ic-020', name: 'Fiery Hot Garlic Chicken', description: 'Chicken tossed in a fiery hot garlic sauce.', price: 350, image: IMG.hotGarlicChicken, imageAlt: 'Hot garlic chicken', diet: 'non-veg', spice: 'hot', serves: '1 plate' },
      { id: 'ic-021', name: 'Chicken Salt & Pepper', description: 'Crispy chicken tossed with salt, pepper, and herbs.', price: 337, image: IMG.chickenSaltPepper, imageAlt: 'Chicken salt and pepper', diet: 'non-veg', serves: '1 plate' },
      { id: 'ic-022', name: 'Extra Crispy Fried Chicken', description: 'Double-fried chicken with an extra crunchy coating.', price: 337, image: IMG.friedChicken, imageAlt: 'Extra crispy fried chicken', diet: 'non-veg', serves: '1 plate' },
    ],
  },

  // ─── 5. TANDOOR SE – VEGETARIAN STARTERS ───
  {
    id: 'tandoor-veg',
    label: 'Tandoor Se — Vegetarian Starters',
    shortLabel: 'Tandoor Veg',
    items: [
      { id: 'tv-001', name: 'Smoky Paneer Tikka', description: 'Cottage cheese marinated in spiced yogurt, char-grilled in the tandoor.', price: 279, image: IMG.paneerTikka, imageAlt: 'Smoky paneer tikka skewers', diet: 'veg', spice: 'medium', popular: true, serves: '1 plate' },
      { id: 'tv-002', name: 'Chatpata Achari Paneer Tikka', description: 'Paneer marinated in tangy pickle spices and grilled.', price: 289, image: IMG.achariPaneerTikka, imageAlt: 'Achari paneer tikka', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'tv-003', name: 'Spicy Kalimirch Paneer Tikka', description: 'Paneer tikka with a bold black pepper marinade.', price: 299, image: IMG.kalimirchPaneerTikka, imageAlt: 'Kalimirch paneer tikka', diet: 'veg', spice: 'hot', serves: '1 plate' },
      { id: 'tv-004', name: 'Creamy Paneer Malai Tikka', description: 'Soft paneer marinated in cream and mild spices.', price: 339, image: IMG.paneerMalai, imageAlt: 'Paneer malai tikka', diet: 'veg', serves: '1 plate' },
      { id: 'tv-005', name: 'Char-Grilled Paneer Seekh Kabab', description: 'Paneer seekh kababs grilled in the tandoor.', price: 329, image: IMG.paneerSeekh, imageAlt: 'Paneer seekh kabab', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'tv-006', name: 'Melt-in-mouth Paneer Malai Seekh', description: 'Soft and creamy paneer malai seekh kababs.', price: 339, image: IMG.paneerMalaiSeekh, imageAlt: 'Paneer malai seekh kabab', diet: 'veg', serves: '1 plate' },
      { id: 'tv-007', name: 'Classic Tandoori Mushroom', description: 'Mushrooms marinated in tandoori spices and grilled.', price: 289, image: IMG.tandooriMushroom, imageAlt: 'Tandoori mushrooms', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'tv-008', name: 'Pepper-Spiced Mushroom Tikka', description: 'Mushroom tikka with a peppery marinade.', price: 289, image: IMG.mushroomTikka, imageAlt: 'Mushroom tikka with pepper', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'tv-009', name: 'Rich Mushroom Malai Tikka', description: 'Creamy mushroom tikka with a malai marinade.', price: 309, image: IMG.mushroomMalaiTikka, imageAlt: 'Mushroom malai tikka', diet: 'veg', serves: '1 plate' },
      { id: 'tv-010', name: 'Crispy Hara Bhara Kabab', description: 'Spinach and pea patties, crispy outside and soft inside.', price: 289, image: IMG.haraBhara, imageAlt: 'Hara bhara kabab', diet: 'veg', serves: '1 plate' },
      { id: 'tv-011', name: 'Signature Dahi Ke Kabab', description: 'Hung curd kababs with a melt-in-mouth texture.', price: 309, image: IMG.dahiKeKabab, imageAlt: 'Dahi ke kabab', diet: 'veg', chefSpecial: true, serves: '1 plate' },
      { id: 'tv-012', name: "Popular's Spl. Veg Seekh", description: 'Our special vegetable seekh kababs grilled in the tandoor.', price: 289, image: IMG.vegSeekh, imageAlt: 'Veg seekh kabab', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'tv-013', name: 'Rich Veg Malai Seekh Kabab', description: 'Creamy vegetable seekh kababs with a malai glaze.', price: 309, image: IMG.vegMalaiSeekh, imageAlt: 'Veg malai seekh kabab', diet: 'veg', serves: '1 plate' },
      { id: 'tv-014', name: 'Char-Roasted Aloo Gobhi', description: 'Potatoes and cauliflower roasted in the tandoor.', price: 219, image: IMG.alooGobhi, imageAlt: 'Char-roasted aloo gobhi', diet: 'veg', spice: 'mild', serves: '1 plate' },
    ],
  },

  // ─── 6. TANDOOR SE – NON-VEG STARTERS ───
  {
    id: 'tandoor-nonveg',
    label: 'Tandoor Se — Non-Veg Starters',
    shortLabel: 'Tandoor Non-Veg',
    items: [
      { id: 'tn-001', name: 'Signature Tandoori Chicken (H/F)', description: 'Half / Full — classic tandoori chicken marinated in yogurt and spices.', price: 369, priceFull: 649, image: IMG.tandooriChicken, imageAlt: 'Tandoori chicken with lime', diet: 'non-veg', spice: 'medium', popular: true, serves: 'Half / Full' },
      { id: 'tn-002', name: 'Creamy Afghani Tandoori Chicken (H/F)', description: 'Half / Full — chicken in a creamy Afghani marinade, char-grilled.', price: 389, priceFull: 679, image: IMG.afghaniChicken, imageAlt: 'Afghani tandoori chicken', diet: 'non-veg', serves: 'Half / Full' },
      { id: 'tn-003', name: 'Smokey Chicken Tikka', description: 'Boneless chicken marinated in spices and char-grilled.', price: 349, image: IMG.chickenTikka, imageAlt: 'Chicken tikka skewers', diet: 'non-veg', spice: 'medium', popular: true, serves: '1 plate' },
      { id: 'tn-004', name: 'Tangy Achari Chicken Tikka', description: 'Chicken tikka with a tangy pickle-spice marinade.', price: 349, image: IMG.achariChickenTikka, imageAlt: 'Achari chicken tikka', diet: 'non-veg', spice: 'medium', serves: '1 plate' },
      { id: 'tn-005', name: 'Green Chicken Tikka', description: 'Chicken tikka marinated in a fresh green herb paste.', price: 349, image: IMG.greenChickenTikka, imageAlt: 'Green chicken tikka', diet: 'non-veg', spice: 'mild', serves: '1 plate' },
      { id: 'tn-006', name: 'Fiery Chicken Angara Tikka', description: 'Spicy chicken tikka with a smoky fiery marinade.', price: 349, image: IMG.chickenAngaraTikka, imageAlt: 'Chicken angara tikka', diet: 'non-veg', spice: 'hot', serves: '1 plate' },
      { id: 'tn-007', name: 'Pepper-crusted Chicken Kalimirch Tikka', description: 'Chicken tikka with a bold black pepper crust.', price: 369, image: IMG.chickenKalimirchTikka, imageAlt: 'Chicken kalimirch tikka', diet: 'non-veg', spice: 'hot', serves: '1 plate' },
      { id: 'tn-008', name: 'Silky Chicken Malai Tikka', description: 'Soft chicken tikka in a creamy malai marinade.', price: 369, image: IMG.chickenMalaiTikka, imageAlt: 'Chicken malai tikka', diet: 'non-veg', serves: '1 plate' },
      { id: 'tn-009', name: 'Nawabi Chicken Reshmi Tikka', description: 'Silky chicken tikka with a royal Nawabi marinade.', price: 369, image: IMG.chickenReshmiTikka, imageAlt: 'Chicken reshmi tikka', diet: 'non-veg', serves: '1 plate' },
      { id: 'tn-010', name: 'Kalimirch Afghani Chicken', description: 'Afghani chicken with a black pepper twist.', price: 389, image: IMG.kalimirchAfghaniChicken, imageAlt: 'Kalimirch Afghani chicken', diet: 'non-veg', spice: 'medium', serves: '1 plate' },
      { id: 'tn-011', name: 'Juicy Chicken Seekh Kabab', description: 'Minced chicken seekh kababs grilled in the tandoor.', price: 349, image: IMG.chickenSeekh, imageAlt: 'Chicken seekh kabab skewers', diet: 'non-veg', spice: 'medium', serves: '1 plate' },
      { id: 'tn-012', name: 'Royal Afghani Seekh Kabab', description: 'Afghani-style seekh kabab with a creamy marinade.', price: 369, image: IMG.afghaniSeekh, imageAlt: 'Afghani seekh kabab', diet: 'non-veg', serves: '1 plate' },
      { id: 'tn-013', name: 'Dineout Spl. Mutton Seekh Kabab', description: 'Premium mutton seekh kabab with our special masala.', price: 519, image: IMG.muttonSeekh, imageAlt: 'Mutton seekh kabab', diet: 'non-veg', spice: 'medium', chefSpecial: true, serves: '1 plate' },
    ],
  },

  // ─── 7. VEGETARIAN DELIGHTS – INDIAN MAIN COURSE ───
  {
    id: 'veg-main',
    label: 'Vegetarian Delights — Indian Main Course',
    shortLabel: 'Indian Veg Main Course',
    items: [
      { id: 'vm-001', name: 'Creamy Paneer Butter Masala', description: 'Cottage cheese in a rich tomato and butter gravy.', price: 349, image: IMG.paneerButterMasala, imageAlt: 'Paneer butter masala', diet: 'veg', spice: 'mild', popular: true, serves: '1 bowl' },
      { id: 'vm-002', name: 'Traditional Kadhai Paneer', description: 'Paneer cooked with bell peppers in a kadhai masala.', price: 369, image: IMG.kadhaiPaneer, imageAlt: 'Kadhai paneer with bell peppers', diet: 'veg', spice: 'medium', serves: '1 bowl' },
      { id: 'vm-003', name: 'Sahi Paneer Royal', description: 'Royal paneer curry in a rich and creamy gravy.', price: 369, image: IMG.sahiPaneer, imageAlt: 'Sahi paneer royal', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-004', name: 'Luscious Paneer Lababdar', description: 'Paneer in a luscious gravy with cream and spices.', price: 389, image: IMG.paneerLababdar, imageAlt: 'Paneer lababdar', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-005', name: 'Char-Grilled Paneer Tikka Masala', description: 'Tandoori paneer tikka simmered in a spiced gravy.', price: 339, image: IMG.paneerTikkaMasala, imageAlt: 'Paneer tikka masala', diet: 'veg', spice: 'medium', serves: '1 bowl' },
      { id: 'vm-006', name: "Popular's Special Paneer Punjabi", description: 'Our signature Punjabi-style paneer curry.', price: 379, image: IMG.paneerPunjabi, imageAlt: 'Paneer Punjabi special', diet: 'veg', spice: 'medium', popular: true, serves: '1 bowl' },
      { id: 'vm-007', name: 'Spicy Paneer Kolhapuri', description: 'Fiery Kolhapuri-style paneer with bold spices.', price: 379, image: IMG.paneerKolhapuri, imageAlt: 'Paneer Kolhapuri', diet: 'veg', spice: 'hot', serves: '1 bowl' },
      { id: 'vm-008', name: 'Authentic Paneer Handi', description: 'Paneer slow-cooked in a traditional handi.', price: 329, image: IMG.paneerHandi, imageAlt: 'Paneer handi', diet: 'veg', spice: 'medium', serves: '1 bowl' },
      { id: 'vm-009', name: 'Rich Paneer Do Pyaza', description: 'Paneer curry with generous onions and rich gravy.', price: 329, image: IMG.paneerDoPyaza, imageAlt: 'Paneer do pyaza', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-010', name: 'Classic Paneer Mutter Masala', description: 'Paneer and green peas in a classic masala gravy.', price: 339, image: IMG.paneerMutterMasala, imageAlt: 'Paneer mutter masala', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-011', name: 'Melt-in-Mouth Paneer Kofta', description: 'Soft paneer kofta balls in a rich gravy.', price: 339, image: IMG.paneerKofta, imageAlt: 'Paneer kofta in gravy', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-012', name: 'Rich Veg Malai Kofta', description: 'Vegetable kofta in a creamy malai gravy.', price: 309, image: IMG.vegMalaiKofta, imageAlt: 'Veg malai kofta', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-013', name: 'Creamy Mushroom Butter Masala', description: 'Mushrooms in a rich butter and tomato gravy.', price: 329, image: IMG.mushroomMasala, imageAlt: 'Mushroom butter masala', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-014', name: 'Smoky Mushroom Tikka Masala', description: 'Tandoori mushroom tikka in a spiced gravy.', price: 329, image: IMG.mushroomTikkaMasala, imageAlt: 'Mushroom tikka masala', diet: 'veg', spice: 'medium', serves: '1 bowl' },
      { id: 'vm-015', name: 'Fresh Mushroom Mutter Masala', description: 'Mushrooms and green peas in a flavorful masala.', price: 299, image: IMG.mushroomMutterMasala, imageAlt: 'Mushroom mutter masala', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-016', name: 'Rich Mushroom Do Pyaza', description: 'Mushroom curry with double the onions.', price: 299, image: IMG.mushroomDoPyaza, imageAlt: 'Mushroom do pyaza', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-017', name: 'Baby Corn Mushroom Masala', description: 'Baby corn and mushrooms in a spiced gravy.', price: 329, image: IMG.babyCornMushroomMasala, imageAlt: 'Baby corn mushroom masala', diet: 'veg', spice: 'medium', serves: '1 bowl' },
      { id: 'vm-018', name: 'Slow-Cooked Mix Veg Handi', description: 'Seasonal vegetables slow-cooked in a handi.', price: 259, image: IMG.mixVeg, imageAlt: 'Mix veg handi', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-019', name: 'Homestyle Bhindi Do Pyaza', description: 'Okra cooked with onions in a homestyle masala.', price: 209, image: IMG.bhindi, imageAlt: 'Bhindi do pyaza', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-020', name: 'Traditional Aloo Dum', description: 'Potatoes in a traditional spicy dum masala.', price: 209, image: IMG.alooDum, imageAlt: 'Aloo dum masala', diet: 'veg', spice: 'medium', serves: '1 bowl' },
      { id: 'vm-021', name: 'Classic Aloo Gobhi Masala', description: 'Potatoes and cauliflower in a classic masala.', price: 219, image: IMG.alooGobhiMasala, imageAlt: 'Aloo gobhi masala', diet: 'veg', spice: 'mild', serves: '1 bowl' },
      { id: 'vm-022', name: 'Punjabi Chole Masala', description: 'Punjabi-style chickpeas in a robust masala gravy.', price: 209, image: IMG.chole, imageAlt: 'Punjabi chole masala', diet: 'veg', spice: 'medium', serves: '1 bowl' },
    ],
  },

  // ─── 8. ROYAL CURRIES – NON-VEG MAIN COURSE ───
  {
    id: 'nonveg-main',
    label: 'Royal Curries — Non-Veg Main Course',
    shortLabel: 'Non-Veg Main Course',
    items: [
      { id: 'nv-001', name: "Patna's Spl. Chicken Ahunna", description: '1kg — Patna\u2019s signature chicken Ahunna, slow-cooked with rich spices.', price: 1299, image: IMG.chickenAhunna, imageAlt: 'Chicken Ahunna curry', diet: 'non-veg', spice: 'medium', chefSpecial: true, serves: '1kg' },
      { id: 'nv-002', name: 'Signature Chicken Dehati', description: '8pcs — rustic village-style chicken curry with bold spices.', price: 809, image: IMG.chickenDehati, imageAlt: 'Chicken dehati curry', diet: 'non-veg', spice: 'hot', serves: '8 pieces' },
      { id: 'nv-003', name: 'Classic Butter Chicken Masala', description: '4pcs — tandoori chicken in a rich tomato and butter gravy.', price: 419, image: IMG.butterChicken, imageAlt: 'Butter chicken masala', diet: 'non-veg', spice: 'mild', popular: true, serves: '4 pieces' },
      { id: 'nv-004', name: 'Smoky Chicken Tikka Masala', description: '4pcs — char-grilled chicken tikka in a spiced gravy.', price: 399, image: IMG.chickenTikkaMasalaCurry, imageAlt: 'Chicken tikka masala', diet: 'non-veg', spice: 'medium', serves: '4 pieces' },
      { id: 'nv-005', name: 'Authentic Chicken Handi', description: '4pcs — chicken slow-cooked in a traditional handi.', price: 389, image: IMG.chickenHandiCurry, imageAlt: 'Chicken handi curry', diet: 'non-veg', spice: 'medium', serves: '4 pieces' },
      { id: 'nv-006', name: 'Fiery Chicken Kolhapuri', description: '4pcs — bold Kolhapuri-style spicy chicken curry.', price: 389, image: IMG.chickenKolhapuriCurry, imageAlt: 'Chicken Kolhapuri', diet: 'non-veg', spice: 'hot', serves: '4 pieces' },
      { id: 'nv-007', name: 'Bengal Style Chicken Kassa', description: '4pcs — Bengali-style chicken in a thick roasted masala.', price: 389, image: IMG.chickenKassa, imageAlt: 'Chicken kassa', diet: 'non-veg', spice: 'medium', serves: '4 pieces' },
      { id: 'nv-008', name: 'Chicken Do Pyaza', description: '4pcs — chicken curry with generous onions and rich gravy.', price: 379, image: IMG.chickenDoPyazaCurry, imageAlt: 'Chicken do pyaza', diet: 'non-veg', spice: 'mild', serves: '4 pieces' },
      { id: 'nv-009', name: 'Slow-Cooked Chicken Istu', description: '4pcs — homestyle chicken stew slow-cooked with spices.', price: 389, image: IMG.chickenIstu, imageAlt: 'Chicken istu stew', diet: 'non-veg', spice: 'mild', serves: '4 pieces' },
      { id: 'nv-010', name: 'Homestyle Chicken Curry', description: '2pcs — classic homestyle chicken curry with aromatic spices.', price: 199, image: IMG.chickenCurry, imageAlt: 'Homestyle chicken curry', diet: 'non-veg', spice: 'medium', popular: true, serves: '2 pieces' },
      { id: 'nv-011', name: 'Rich Chicken Masala', description: '2pcs — chicken in a rich and flavorful masala gravy.', price: 199, image: IMG.chickenMasalaCurry, imageAlt: 'Chicken masala', diet: 'non-veg', spice: 'medium', serves: '2 pieces' },
      { id: 'nv-012', name: 'Rich Mutton Rogan Josh', description: '4pcs — Kashmiri-style mutton in a rich red gravy.', price: 509, image: IMG.muttonCurry, imageAlt: 'Mutton rogan josh', diet: 'non-veg', spice: 'medium', popular: true, serves: '4 pieces' },
      { id: 'nv-013', name: 'Tender Mutton Do Pyaza', description: '4pcs — mutton curry with double the onions.', price: 509, image: IMG.muttonDoPyazaCurry, imageAlt: 'Mutton do pyaza', diet: 'non-veg', spice: 'medium', serves: '4 pieces' },
      { id: 'nv-014', name: 'Slow-Cooked Mutton Handi', description: '4pcs — mutton slow-cooked in a traditional handi.', price: 509, image: IMG.muttonHandiCurry, imageAlt: 'Mutton handi curry', diet: 'non-veg', spice: 'medium', serves: '4 pieces' },
      { id: 'nv-015', name: 'Spicy Homestyle Egg Curry', description: '4pcs — boiled eggs in a spicy homestyle masala gravy.', price: 219, image: IMG.eggCurry, imageAlt: 'Spicy egg curry', diet: 'egg', spice: 'hot', serves: '4 pieces' },
      { id: 'nv-016', name: 'Dhaba Style Egg Masala', description: '2pcs — dhaba-style egg curry with a rustic masala.', price: 179, image: IMG.eggMasala, imageAlt: 'Dhaba style egg masala', diet: 'egg', spice: 'medium', serves: '2 pieces' },
    ],
  },

  // ─── 9. BREADS AND ROTI – FRESH FROM THE TANDOOR ───
  {
    id: 'breads',
    label: 'Breads and Roti — Fresh from the Tandoor',
    shortLabel: 'Breads & Roti',
    items: [
      { id: 'bd-001', name: 'Soft Tawa Roti', description: 'Whole wheat flatbread cooked on a tawa.', price: 29, image: IMG.tawaRoti, imageAlt: 'Tawa roti', diet: 'veg', serves: '1 piece' },
      { id: 'bd-002', name: 'Traditional Tandoori Roti', description: 'Whole wheat bread baked in the clay tandoor.', price: 39, image: IMG.tandooriRoti, imageAlt: 'Tandoori roti', diet: 'veg', serves: '1 piece' },
      { id: 'bd-003', name: 'Butter Tandoori Roti', description: 'Tandoori roti brushed with fresh butter.', price: 49, image: IMG.butterTandooriRoti, imageAlt: 'Butter tandoori roti', diet: 'veg', serves: '1 piece' },
      { id: 'bd-004', name: 'Soft Plain Naan', description: 'Leavened bread baked in the tandoor.', price: 59, image: IMG.naan, imageAlt: 'Plain naan', diet: 'veg', serves: '1 piece' },
      { id: 'bd-005', name: 'Rich Butter Naan', description: 'Naan brushed generously with butter.', price: 79, image: IMG.butterNaan, imageAlt: 'Butter naan', diet: 'veg', popular: true, serves: '1 piece' },
      { id: 'bd-006', name: 'Roasted Garlic Butter Naan', description: 'Naan topped with roasted garlic and butter.', price: 89, image: IMG.garlicNaan, imageAlt: 'Garlic butter naan', diet: 'veg', serves: '1 piece' },
      { id: 'bd-007', name: 'Flaky Laccha Paratha', description: 'Multi-layered flaky paratha, crispy and buttery.', price: 89, image: IMG.lacchaParatha, imageAlt: 'Laccha paratha', diet: 'veg', serves: '1 piece' },
      { id: 'bd-008', name: 'Onion Stuffed Kulcha', description: 'Kulcha stuffed with spiced onion filling.', price: 89, image: IMG.onionKulcha, imageAlt: 'Onion stuffed kulcha', diet: 'veg', serves: '1 piece' },
      { id: 'bd-009', name: 'Premium Paneer Stuffed Kulcha', description: 'Kulcha stuffed with a rich paneer filling.', price: 99, image: IMG.paneerKulcha, imageAlt: 'Paneer stuffed kulcha', diet: 'veg', serves: '1 piece' },
      { id: 'bd-010', name: 'Rich Paneer Stuffed Paratha', description: 'Paratha stuffed with spiced paneer, served with butter.', price: 109, image: IMG.paratha, imageAlt: 'Paneer stuffed paratha', diet: 'veg', serves: '1 piece' },
      { id: 'bd-011', name: 'Chicken Keema Stuffed Butter Naan', description: 'Naan stuffed with spiced chicken keema and butter.', price: 129, image: IMG.keemaNaan, imageAlt: 'Chicken keema stuffed naan', diet: 'non-veg', spice: 'medium', serves: '1 piece' },
    ],
  },

  // ─── 10. FRESH GREENS – SALAD & RAITA ───
  {
    id: 'salad-raita',
    label: 'Fresh Greens — Salad & Raita',
    shortLabel: 'Salad & Raita',
    items: [
      { id: 'sr-001', name: 'Farm Fresh Green Salad', description: 'Fresh cucumber, tomato, onion, and lemon.', price: 99, image: IMG.salad, imageAlt: 'Fresh green salad with vegetables', diet: 'veg', serves: '1 plate' },
      { id: 'sr-002', name: 'Fire-Roasted Papad (2pcs)', description: 'Papad roasted over an open flame.', price: 69, image: IMG.papad, imageAlt: 'Roasted papad', diet: 'veg', serves: '2 pieces' },
      { id: 'sr-003', name: 'Crispy Fried Papad (2pcs)', description: 'Papad deep-fried to crispy perfection.', price: 79, image: IMG.friedPapad, imageAlt: 'Fried papad', diet: 'veg', serves: '2 pieces' },
      { id: 'sr-004', name: 'Chatpata Masala Papad (2pcs)', description: 'Papad topped with chatpata masala and chutney.', price: 89, image: IMG.masalaPapad, imageAlt: 'Masala papad with toppings', diet: 'veg', serves: '2 pieces' },
      { id: 'sr-005', name: 'Spicy Masala Peanut', description: 'Roasted peanuts tossed with spicy masala.', price: 89, image: IMG.masalaPeanut, imageAlt: 'Masala peanuts', diet: 'veg', spice: 'medium', serves: '1 bowl' },
      { id: 'sr-006', name: 'Chilled Boondi Raita', description: 'Yogurt with soft boondi and spices.', price: 109, image: IMG.raita, imageAlt: 'Boondi raita in a bowl', diet: 'veg', serves: '1 bowl' },
      { id: 'sr-007', name: 'Garden Fresh Mix Veg Raita', description: 'Yogurt with fresh chopped vegetables and spices.', price: 129, image: IMG.mixVegRaita, imageAlt: 'Mix veg raita', diet: 'veg', serves: '1 bowl' },
      { id: 'sr-008', name: 'Cooling Kheera Raita', description: 'Yogurt with grated cucumber and cumin.', price: 89, image: IMG.kheeraRaita, imageAlt: 'Kheera raita', diet: 'veg', serves: '1 bowl' },
      { id: 'sr-009', name: 'Refreshing Poodina Raita', description: 'Yogurt with fresh mint and spices.', price: 89, image: IMG.poodinaRaita, imageAlt: 'Poodina mint raita', diet: 'veg', serves: '1 bowl' },
    ],
  },

  // ─── 11. DESSERTS ───
  {
    id: 'desserts',
    label: 'Desserts',
    shortLabel: 'Desserts',
    items: [
      { id: 'ds-001', name: 'Warm Gulab Jamun (2pcs)', description: 'Warm milk-solid dumplings soaked in rose-flavored syrup.', price: 79, image: IMG.gulabJamun, imageAlt: 'Gulab jamun in syrup', diet: 'veg', popular: true, serves: '2 pieces' },
      { id: 'ds-002', name: 'Spongy Rasgulla (2pcs)', description: 'Soft spongy rasgulla in light sugar syrup.', price: 69, image: IMG.rasgulla, imageAlt: 'Rasgulla in syrup', diet: 'veg', serves: '2 pieces' },
      { id: 'ds-003', name: 'Rich Saffron Ras-Malai (2pcs)', description: 'Soft cheese patties in saffron milk with nuts.', price: 129, image: IMG.rasmalai, imageAlt: 'Saffron ras-malai with nuts', diet: 'veg', chefSpecial: true, serves: '2 pieces' },
      { id: 'ds-004', name: 'Choice of Ice Cream', description: 'Pick your favourite ice cream flavour.', price: 69, image: IMG.iceCream, imageAlt: 'Ice cream scoop', diet: 'veg', serves: '1 scoop' },
    ],
  },

  // ─── 12. RICE AND BIRYANI – CLASSICS WITH A CITRUS TWIST ───
  {
    id: 'rice-biryani',
    label: 'Rice and Biryani — Classics with a Citrus Twist',
    shortLabel: 'Rice & Biryani',
    items: [
      { id: 'rb-001', name: 'Steamed Basmati Rice', description: 'Fluffy steamed basmati rice, perfect with any curry.', price: 189, image: IMG.basmatiRice, imageAlt: 'Steamed basmati rice', diet: 'veg', serves: '1 plate' },
      { id: 'rb-002', name: 'Classic Jeera Rice', description: 'Basmati rice tempered with cumin seeds.', price: 199, image: IMG.jeeraRice, imageAlt: 'Jeera rice with cumin', diet: 'veg', serves: '1 plate' },
      { id: 'rb-003', name: 'Classic Peas Mutter Pulao', description: 'Basmati rice cooked with green peas and whole spices.', price: 219, image: IMG.rice, imageAlt: 'Peas pulao with basmati rice', diet: 'veg', serves: '1 plate' },
      { id: 'rb-004', name: 'Classic Veg Fried Rice', description: 'Rice stir-fried with vegetables and soy sauce.', price: 219, image: IMG.friedRice, imageAlt: 'Veg fried rice', diet: 'veg', serves: '1 plate' },
      { id: 'rb-005', name: 'Mushroom Fried Rice', description: 'Fried rice with mushrooms and vegetables.', price: 199, image: IMG.mushroomFriedRice, imageAlt: 'Mushroom fried rice', diet: 'veg', serves: '1 plate' },
      { id: 'rb-006', name: 'Spicy Schezwan Veg Fried Rice', description: 'Fried rice tossed in fiery Schezwan sauce.', price: 219, image: IMG.schezwanFriedRice, imageAlt: 'Schezwan veg fried rice', diet: 'veg', spice: 'hot', serves: '1 plate' },
      { id: 'rb-007', name: "Popular's Special Veg Fried Rice", description: 'Our signature veg fried rice with special masala.', price: 219, image: IMG.specialFriedRice, imageAlt: 'Popular special veg fried rice', diet: 'veg', popular: true, serves: '1 plate' },
      { id: 'rb-008', name: 'Scrambled Egg Fried Rice', description: 'Fried rice with scrambled eggs and vegetables.', price: 219, image: IMG.eggFriedRice, imageAlt: 'Egg fried rice', diet: 'egg', serves: '1 plate' },
      { id: 'rb-009', name: 'Paneer Fried Rice', description: 'Fried rice with paneer cubes and vegetables.', price: 219, image: IMG.paneerFriedRice, imageAlt: 'Paneer fried rice', diet: 'veg', serves: '1 plate' },
      { id: 'rb-010', name: 'Classic Chicken Fried Rice (PSP)', description: 'Fried rice with chicken and vegetables.', price: 219, image: IMG.chickenFriedRice, imageAlt: 'Chicken fried rice', diet: 'non-veg', serves: '1 plate' },
      { id: 'rb-011', name: 'Fiery Schezwan Chicken Fried Rice', description: 'Chicken fried rice tossed in fiery Schezwan sauce.', price: 259, image: IMG.schezwanChickenFriedRice, imageAlt: 'Schezwan chicken fried rice', diet: 'non-veg', spice: 'hot', serves: '1 plate' },
      { id: 'rb-012', name: 'Double Delight Egg & Chicken Fried Rice', description: 'Fried rice with both egg and chicken.', price: 279, image: IMG.eggChickenFriedRice, imageAlt: 'Egg and chicken fried rice', diet: 'non-veg', serves: '1 plate' },
      { id: 'rb-013', name: 'Shahi Veg Dum Biryani', description: 'Fragrant basmati with vegetables, saffron, and whole spices.', price: 259, image: IMG.vegBiryani, imageAlt: 'Shahi veg dum biryani', diet: 'veg', serves: '1 plate' },
      { id: 'rb-014', name: 'Flavorful Egg Dum Biryani', description: 'Dum biryani with boiled eggs and aromatic spices.', price: 289, image: IMG.eggBiryani, imageAlt: 'Egg dum biryani', diet: 'egg', serves: '1 plate' },
      { id: 'rb-015', name: 'Rich Paneer Dum Biryani', description: 'Dum biryani with paneer and rich masala.', price: 309, image: IMG.paneerBiryani, imageAlt: 'Paneer dum biryani', diet: 'veg', serves: '1 plate' },
      { id: 'rb-016', name: 'Nawabi Chicken Dum Biryani', description: 'Dum biryani with marinated chicken, saffron, and whole spices.', price: 329, image: IMG.chickenBiryani, imageAlt: 'Nawabi chicken dum biryani', diet: 'non-veg', popular: true, chefSpecial: true, serves: '1 plate' },
      { id: 'rb-017', name: 'Dineout Mutton Dum Biryani', description: 'Premium mutton dum biryani with fragrant basmati and spices.', price: 499, image: IMG.muttonBiryani, imageAlt: 'Mutton dum biryani', diet: 'non-veg', chefSpecial: true, serves: '1 plate' },
      { id: 'rb-018', name: 'Classic Yellow Dal Tadka', description: 'Yellow lentils tempered with cumin, garlic, and red chili.', price: 199, image: IMG.dalTadka, imageAlt: 'Dal tadka with tempering', diet: 'veg', serves: '1 bowl' },
    ],
  },

  // ─── 13. NOODLES – WOK CLASSICS ───
  {
    id: 'noodles',
    label: 'Noodles — Wok Classics',
    shortLabel: 'Noodles',
    items: [
      { id: 'nd-001', name: 'Veg Hakka Noodles', description: 'Stir-fried noodles with crunchy vegetables.', price: 249, image: IMG.noodles, imageAlt: 'Veg Hakka noodles', diet: 'veg', serves: '1 plate' },
      { id: 'nd-002', name: 'Desi Mix Veg Chowmein', description: 'Indian-style chowmein with mixed vegetables.', price: 239, image: IMG.chowmein, imageAlt: 'Mix veg chowmein', diet: 'veg', serves: '1 plate' },
      { id: 'nd-003', name: 'Spicy Schezwan Veg Noodles', description: 'Noodles tossed in fiery Schezwan sauce with vegetables.', price: 239, image: IMG.schezwanNoodles, imageAlt: 'Schezwan veg noodles', diet: 'veg', spice: 'hot', serves: '1 plate' },
      { id: 'nd-004', name: 'Fiery Garlic Veg Noodles', description: 'Noodles tossed in garlic with vegetables.', price: 239, image: IMG.garlicNoodles, imageAlt: 'Garlic veg noodles', diet: 'veg', spice: 'medium', serves: '1 plate' },
      { id: 'nd-005', name: 'Paneer Hakka Noodles', description: 'Hakka noodles with paneer and vegetables.', price: 249, image: IMG.paneerNoodles, imageAlt: 'Paneer Hakka noodles', diet: 'veg', serves: '1 plate' },
      { id: 'nd-006', name: 'Mushroom Hakka Noodles', description: 'Hakka noodles with mushrooms and vegetables.', price: 249, image: IMG.mushroomNoodles, imageAlt: 'Mushroom Hakka noodles', diet: 'veg', serves: '1 plate' },
      { id: 'nd-007', name: "Popular's Special Veg Noodles", description: 'Our signature veg noodles with special masala.', price: 259, image: IMG.specialNoodles, imageAlt: 'Popular special veg noodles', diet: 'veg', popular: true, serves: '1 plate' },
      { id: 'nd-008', name: 'Classic Chicken Hakka Noodles', description: 'Hakka noodles with chicken and vegetables.', price: 299, image: IMG.chickenNoodles, imageAlt: 'Chicken Hakka noodles', diet: 'non-veg', serves: '1 plate' },
      { id: 'nd-009', name: 'Schezwan Tossed Chicken Noodles', description: 'Chicken noodles tossed in fiery Schezwan sauce.', price: 289, image: IMG.schezwanChickenNoodles, imageAlt: 'Schezwan chicken noodles', diet: 'non-veg', spice: 'hot', serves: '1 plate' },
      { id: 'nd-010', name: 'Hot Garlic Chicken Noodles', description: 'Chicken noodles tossed in a hot garlic sauce.', price: 289, image: IMG.garlicChickenNoodles, imageAlt: 'Hot garlic chicken noodles', diet: 'non-veg', spice: 'hot', serves: '1 plate' },
      { id: 'nd-011', name: 'Egg & Chicken Tossed Noodles', description: 'Noodles tossed with egg and chicken.', price: 299, image: IMG.eggChickenNoodles, imageAlt: 'Egg and chicken noodles', diet: 'non-veg', serves: '1 plate' },
      { id: 'nd-012', name: "Popular's Signature Chicken Noodles", description: 'Our signature chicken noodles with special masala.', price: 309, image: IMG.signatureChickenNoodles, imageAlt: 'Popular signature chicken noodles', diet: 'non-veg', chefSpecial: true, serves: '1 plate' },
    ],
  },
];
