/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        script: ['"Caveat"', 'cursive'],
      },
      colors: {
        charcoal: {
          950: '#0c0a09',
          900: '#1c1917',
          800: '#292524',
          700: '#44403c',
          600: '#57534e',
          500: '#78716c',
          400: '#a8a29e',
          300: '#d6d3d1',
          200: '#e7e5e4',
          100: '#f5f5f4',
          50: '#fafaf9',
        },
        plum: {
          50: '#fdf6f3',
          100: '#f9e8e0',
          200: '#f1d0c2',
          300: '#e4a99c',
          400: '#cf7a67',
          500: '#b85a44',
          600: '#9c4533',
          700: '#7c3729',
          800: '#5c2a20',
          900: '#3d1d17',
          950: '#2a1310',
        },
        saffron: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        maroon: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#7f1d1d',
          900: '#5b0e0e',
        },
        gold: {
          50: '#fefce8',
          100: '#fef9c3',
          200: '#fef08a',
          300: '#fde047',
          400: '#facc15',
          500: '#eab308',
          600: '#ca8a04',
          700: '#a16207',
          800: '#854d0e',
          900: '#713f12',
        },
        cream: {
          50: '#fffbf5',
          100: '#fef7ed',
          200: '#fdf0e3',
          300: '#fce8d6',
          400: '#f5e0cc',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'fade-in-down': 'fadeInDown 0.6s ease-out forwards',
        'scale-in': 'scaleIn 0.5s ease-out forwards',
        'slide-in-right': 'slideInRight 0.5s ease-out forwards',
        'shimmer': 'shimmer 2s linear infinite',
        'progress-fill': 'progressFill 2.8s ease-in-out forwards',
        'circle-reveal': 'circleReveal 1.2s ease-out forwards',
        'feature-card-in': 'featureCardIn 0.6s ease-out forwards',
        'spin-slow': 'spin 3s linear infinite',
        'float-corner-tl': 'floatCornerTL 6s ease-in-out infinite',
        'float-corner-tr': 'floatCornerTR 7s ease-in-out infinite',
        'float-corner-bl': 'floatCornerBL 6.5s ease-in-out infinite',
        'float-corner-br': 'floatCornerBR 7.5s ease-in-out infinite',
        'brand-rise': 'brandRise 0.9s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'ring-reveal': 'ringReveal 1.5s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'progress-shine': 'progressShine 2s ease-in-out infinite',
        'sparkle': 'sparkle 2.5s ease-in-out infinite',
        'final-pulse': 'finalPulse 0.6s ease-out forwards',
        'chakri-spin': 'chakriSpin 1.8s linear infinite',
        'chakri-spin-fast': 'chakriSpin 0.8s linear infinite',
        'veg-rotate': 'vegRotate 4s ease-in-out infinite',
        'veg-bounce': 'vegBounce 3s ease-in-out infinite',
        'veg-slide-in': 'vegSlideIn 0.8s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'veg-pop-in': 'vegPopIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'flame-flicker': 'flameFlicker 0.5s ease-in-out infinite',
        'flame-rise': 'flameRise 1.2s ease-out infinite',
        'cook-shake': 'cookShake 0.3s ease-in-out',
        'cook-shake-fast': 'cookShakeFast 0.2s ease-in-out',
        'progress-glow': 'progressGlow 0.5s ease-out forwards',
        'complete-burst': 'completeBurst 0.8s ease-out forwards',
        'veg-burst': 'vegBurst 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'spin-medium': 'spin 2s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        progressFill: {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
        circleReveal: {
          '0%': { opacity: '0', transform: 'scale(0.6) rotate(-15deg)' },
          '100%': { opacity: '1', transform: 'scale(1) rotate(0deg)' },
        },
        featureCardIn: {
          '0%': { opacity: '0', transform: 'translateY(20px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        floatCornerTL: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '50%': { transform: 'translate(8px, 6px) rotate(1deg)' },
        },
        floatCornerTR: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '50%': { transform: 'translate(-8px, 6px) rotate(-1deg)' },
        },
        floatCornerBL: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '50%': { transform: 'translate(8px, -6px) rotate(-1deg)' },
        },
        floatCornerBR: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '50%': { transform: 'translate(-8px, -6px) rotate(1deg)' },
        },
        brandRise: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        ringReveal: {
          '0%': { opacity: '0', transform: 'scale(0.8)', borderStyle: 'solid' },
          '50%': { opacity: '0.8', transform: 'scale(1.05)' },
          '100%': { opacity: '0.6', transform: 'scale(1)', borderStyle: 'dashed' },
        },
        progressShine: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(300%)' },
        },
        sparkle: {
          '0%, 100%': { opacity: '0', transform: 'scale(0.5)' },
          '50%': { opacity: '0.9', transform: 'scale(1)' },
        },
        finalPulse: {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(249, 115, 22, 0.4)' },
          '50%': { transform: 'scale(1.03)', boxShadow: '0 0 0 8px rgba(249, 115, 22, 0)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(249, 115, 22, 0)' },
        },
        chakriSpin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        vegRotate: {
          '0%, 100%': { transform: 'rotate(-8deg) translateY(0)' },
          '50%': { transform: 'rotate(8deg) translateY(-6px)' },
        },
        vegBounce: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-10px) rotate(5deg)' },
        },
        vegSlideIn: {
          '0%': { opacity: '0', transform: 'translateX(-30px) rotate(-20deg) scale(0.8)' },
          '100%': { opacity: '0.85', transform: 'translateX(0) rotate(0deg) scale(1)' },
        },
        vegPopIn: {
          '0%': { opacity: '0', transform: 'scale(0.3) rotate(-30deg)' },
          '60%': { opacity: '0.85', transform: 'scale(1.1) rotate(5deg)' },
          '100%': { opacity: '0.85', transform: 'scale(1) rotate(0deg)' },
        },
        flameFlicker: {
          '0%, 100%': { transform: 'scaleY(1) scaleX(1) opacity(0.9)' },
          '25%': { transform: 'scaleY(1.15) scaleX(0.95) opacity(1)' },
          '50%': { transform: 'scaleY(0.9) scaleX(1.05) opacity(0.8)' },
          '75%': { transform: 'scaleY(1.1) scaleX(0.98) opacity(1)' },
        },
        flameRise: {
          '0%': { transform: 'translateY(0) scale(0.8)', opacity: '0' },
          '20%': { opacity: '1' },
          '80%': { opacity: '0.7' },
          '100%': { transform: 'translateY(-30px) scale(1.2)', opacity: '0' },
        },
        cookShake: {
          '0%, 100%': { transform: 'translateX(0) rotate(0deg)' },
          '25%': { transform: 'translateX(-3px) rotate(-1deg)' },
          '50%': { transform: 'translateX(3px) rotate(1deg)' },
          '75%': { transform: 'translateX(-2px) rotate(-0.5deg)' },
        },
        cookShakeFast: {
          '0%, 100%': { transform: 'translateX(0) rotate(0deg)' },
          '25%': { transform: 'translateX(-2px) rotate(-0.5deg)' },
          '50%': { transform: 'translateX(2px) rotate(0.5deg)' },
          '75%': { transform: 'translateX(-1px) rotate(-0.3deg)' },
        },
        progressGlow: {
          '0%': { boxShadow: '0 0 0 0 rgba(249, 115, 22, 0)' },
          '50%': { boxShadow: '0 0 12px 4px rgba(249, 115, 22, 0.4)' },
          '100%': { boxShadow: '0 0 0 0 rgba(249, 115, 22, 0)' },
        },
        completeBurst: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '50%': { transform: 'scale(1.2)', opacity: '0.8' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
        vegBurst: {
          '0%': { transform: 'translate(0, 0) scale(0.5) rotate(0deg)', opacity: '0' },
          '30%': { opacity: '1' },
          '100%': { transform: 'var(--burst-x, 40px) var(--burst-y, -40px) scale(1) rotate(var(--burst-r, 180deg))', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};
